{******************************************************************************}
{*  Days.inc                                                                  *}
{*  Revolutionary Confederation of Anarcho Syndicalists                       *}
{*  Written by: black.rabbit 2011                                             *}
{******************************************************************************}
resourcestring
    WeekDay1 = 'Понедельник';
    WeekDay2 = 'Вторник';
    WeekDay3 = 'Среда';
    WeekDay4 = 'Четверг';
    WeekDay5 = 'Пятница';
    WeekDay6 = 'Суббота';
    WeekDay7 = 'Воскресенье';

resourcestring
    WD1 = 'Пон.';
    WD2 = 'Вт.';
    WD3 = 'Ср.';
    WD4 = 'Чтв.';
    WD5 = 'Птн.';
    WD6 = 'Суб.';
    WD7 = 'Вск.';
