{******************************************************************************}
{*  Months.inc                                                                *}
{*  Revolutionary Confederation of Anarcho Syndicalists                       *}
{*  Written by: black.rabbit 2011                                             *}
{******************************************************************************}
resourcestring
    MonthJan = 'Январь';
    MonthFeb = 'Февраль';
    MonthMar = 'Март';
    MonthApr = 'Апрель';
    MonthMay = 'Май';
    MonthJun = 'Июнь';
    MonthJul = 'Июль';
    MonthAug = 'Август';
    MonthSep = 'Сентябрь';
    MonthOct = 'Октябрь';
    MonthNov = 'Ноябрь';
    MonthDec = 'Декабрь';

resourcestring
    Jan = 'Янв';
    Feb = 'Фев';
    Mar = 'Мрт';
    Apr = 'Апр';
    May = 'Май';
    Jun = 'Июн';
    Jul = 'Июл';
    Aug = 'Авг';
    Sep = 'Сен';
    Oct = 'Окт';
    Nov = 'Ноя';
    Dec = 'Дек';

resourcestring
    JanL = 'Января';
    FebL = 'Февраля';
    MarL = 'Марта';
    AprL = 'Апреля';
    MayL = 'Мая';
    JunL = 'Июня';
    JulL = 'Июля';
    AugL = 'Августа';
    SepL = 'Сентября';
    OctL = 'Октября';
    NovL = 'Ноября';
    DecL = 'Декабря';