{******************************************************************************}
{*  gzlib.project.inc                                                         *}
{*  Revolutionary Confederation of Anarcho Syndicalists                       *}
{*  Written by: black.rabbit 2012                                             *}
{******************************************************************************}
gzlibex    in 'gzlib/gZLibEx.pas',
gzlibexapi in 'gzlib/gZLibExApi.pas',
gzlibexgz  in 'gzlib/gZLibExGZ.pas',