{******************************************************************************}
{*  gzlib.uses.inc                                                            *}
{*  Revolutionary Confederation of Anarcho Syndicalists                       *}
{*  Written by: black.rabbit 2012                                             *}
{******************************************************************************}
{$IFDEF GZIP}
    gzlibex,
    gzlibexapi,
    gzlibexgz,
{$ENDIF GZIP}
