{******************************************************************************}
{*  CategoriesTree.err.inc                                                    *}
{*  Revolutionary Confederation of Anarcho Syndicalists                       *}
{*  Written by: black.rabbit 2011                                             *}
{******************************************************************************}
{ ошибки при работе с деревом категорий }
resourcestring
    ERR_CATEGORIES_TREE_INCORRECT_DATABASE = 'Не инициализирован объект БД!';
    ERR_CATEGORIES_TREE_INCORRECT_NODES    = 'Объект дерева не инициализирован!';
    ERR_CATEGORIES_TREE_CREATE             = 'Ошибка построения дерева категорий!';
    ERR_CATEGORIES_TREE_DELETE             = 'Ошибка очистки дерева категорий!';
    ERR_CATEGORIES_TREE_INCORRECT_ID       = 'Узел дерева содержит некорректный идентификатор!';
    ERR_CATEGORIES_TREE_INCORRECT_NODE     = 'Объект узла дерева не инициализирован!';
    ERR_CATEGORIES_TREE_GET_NODE_ID        = 'Ошибка получения идентификатора из узла дерева!';