{******************************************************************************}
{*  Engine.project.inc                                                        *}
{*  Revolutionary Confederation of Anarcho Syndicalists                       *}
{*  Written by: black.rabbit 2011                                             *}
{******************************************************************************}
    Engine in 'engine/Engine.pas',
