{******************************************************************************}
{*  TCategories.err.inc                                                       *}
{*  Revolutionary Confederation of Anarcho Syndicalists                       *}
{*  Written by: black.rabbit 2011                                             *}
{******************************************************************************}
resourcestring
    ERR_TCATEGORIES                  = 'Ошибка списка категорий!';
    ERR_TCATEGORIES_CREATE           = 'Ошибка создания списка категорий!';
    ERR_TCATEGORIES_INVALID_DATABASE = 'Некорректный объект БД!';
    ERR_TCATEGORIES_INVALID_STREAM   = 'Некорректный поток!';
    ERR_TCATEGORIES_DESTROY          = 'Ошибка уничтожения списка категорий!';
    ERR_TCATEGORIES_CHECK            = 'Ошибка валидации категории!';
    ERR_TCATEGORIES_GET_ITEM_AT      = 'Ошибка чтения категории по индексу!';
    ERR_TCATEGORIES_GET_ITEM_OF      = 'Ошибка чтения категории по имени!';
    ERR_TCATEGORIES_GET_ITEM_ON      = 'Ошибка чтения категории по идентификатору!';
    ERR_TCATEGORIES_SET_ITEM_AT      = 'Ошибка записи категории по индексу!';
    ERR_TCATEGORIES_SET_ITEM_OF      = 'Ошибка записи категории по имени!';
    ERR_TCATEGORIES_SET_ITEM_ON      = 'Ошибка записи категории по идентификатору!';
    ERR_TCATEGORIES_ADD              = 'Ошибка добавления категории в список!';
    ERR_TCATEGORIES_ADD_LOAD         = 'Ошибка загрузки категории в список!';
    ERR_TCATEGORIES_ADD_SAVE         = 'Ошибка сохранения категории в список!';
    ERR_TCATEGORIES_FILTER           = 'Ошибка наложения фильтра!';
    ERR_TCATEGORIES_LOAD             = 'Ошибка загрузки списка категорий!';
    ERR_TCATEGORIES_SAVE             = 'Ошибка сохранения списка категорий!';
    ERR_TCATEGORIES_DELETE           = 'Ошибка удаления списка категорий!';
    ERR_TCATEGORIES_DELETE_BY_PARENT = 'Ошибка удаления категорий по предку!';
    ERR_TCATEGORIES_FIND             = 'Ошибка поиска категории по хэшу!';
    ERR_TCATEGORIES_GET_HASH_LIST    = 'Ошибка формирования хэш-таблицы!';
    ERR_TCATEGORIES_REPLACE_PIC      = 'Ошибка замены иконки категории!';
    ERR_TCATEGORIES_TRANSACTION      = 'Ошибка транзакции: '#13#10'%s';