{******************************************************************************}
{*  TCategorieType.err.inc                                                    *}
{*  Revolutionary Confederation of Anarcho Syndicalists                       *}
{*  Written by: black.rabbit 2011                                             *}
{******************************************************************************}
resourcestring
    ERR_TCATEGORIETYPE                        = 'Ошибка типа категории!';
    ERR_TCATEGORIETYPE_GET_ClASS_PROPERTIES   = 'Ошибка получения списка свойств класса типа категорий!';
    ERR_TCATEGORIETYPE_CREATE                 = 'Ошибка создания типа категории!';
    ERR_TCATEGORIETYPE_CREATE_CLASS_TABLE     = 'Ошибка создания таблицы класса типа категорий!';
    ERR_TCATEGORIETYPE_INVALID_DATABASE       = 'Некорректный объект БД!';
    ERR_TCATEGORIETYPE_DESTROY                = 'Ошибка уничтожения типа категории!';
    ERR_TCATEGORIETYPE_REGISTER_PROPERTY      = 'Ошибка регистрации свойства типа категории!';
    ERR_TCATEGORIETYPE_REGISTER_PROPERTIES    = 'Ошибка регистрации списка свойств типа категории!';
    ERR_TCATEGORIETYPE_GET_PROPERTY_AT        = 'Ошибка чтения свойства типа категории по индексу!';
    ERR_TCATEGORIETYPE_GET_PROPERTY_OF        = 'Ошибка чтения свойства типа категории по имени!';
    ERR_TCATEGORIETYPE_SET_PROPERTY_AT        = 'Ошибка записи свойства типа категории по индексу!';
    ERR_TCATEGORIETYPE_SET_PROPERTY_OF        = 'Ошибка записи свойства типа категории по имени!';
    ERR_TCATEGORIETYPE_GET_ID                 = 'Ошибка чтения идентификатора типа категории!';
    ERR_TCATEGORIETYPE_GET_ID_EXTERNAL        = 'Ошибка чтения названия типа категории!';
    ERR_TCATEGORIETYPE_GET_DESCRIPTION        = 'Ошибка чтения описания типа категории!';
    ERR_TCATEGORIETYPE_SET_ID                 = 'Ошибка записи идентификатора типа категории!';
    ERR_TCATEGORIETYPE_SET_ID_EXTERNAL        = 'Ошибка записи названия типа категории!';
    ERR_TCATEGORIETYPE_SET_DESCRIPTION        = 'Ошибка записи описания типа категории!';
    ERR_TCATEGORIETYPE_SET_OBJECT_NAME        = 'Ошибка записи наименования типа категории!';
    ERR_TCATEGORIETYPE_CHECK                  = 'Ошибка валидации типа категории!';
    ERR_TCATEGORIETYPE_LOAD                   = 'Ошибка загрузки типа категории!';
    ERR_TCATEGORIETYPE_SAVE                   = 'Ошибка сохранения типа категории!';
    ERR_TCATEGORIETYPE_DELETE                 = 'Ошибка удаления типа категории!';
    ERR_TCATEGORIETYPE_NOT_UNIQUE_ID          = 'Ошибка дублирования идентификатора типа категории : ''%s'' = ''%s''!';
    ERR_TCATEGORIETYPE_NOT_UNIQUE_ID_EXTERNAL = 'Ошибка дублирования названия типа категории : ''%s'' = ''%s''!';
    ERR_TCATEGORIETYPE_INVALID_ID             = 'Некорректный идентификатор типа категории!';
    ERR_TCATEGORIETYPE_INVALID_ID_EXTERNAL    = 'Некорректный название типа категории!';
    ERR_TCATEGORIETYPE_TRANSACTION            = 'Ошибка транзакции: '#13#10'%s';