{******************************************************************************}
{*  TCategorieStatus.err.inc                                                  *}
{*  Revolutionary Confederation of Anarcho Syndicalists                       *}
{*  Written by: black.rabbit 2011                                             *}
{******************************************************************************}
resourcestring
    ERR_TCATEGORIESTATUS                        = 'Ошибка статуса категории!';
    ERR_TCATEGORIESTATUS_GET_ClASS_PROPERTIES   = 'Ошибка получения списка свойств класса статуса категорий!';
    ERR_TCATEGORIESTATUS_CREATE                 = 'Ошибка создания статуса категории!';
    ERR_TCATEGORIESTATUS_CREATE_CLASS_TABLE     = 'Ошибка создания таблицы класса статуса категорий!';
    ERR_TCATEGORIESTATUS_INVALID_DATABASE       = 'Некорректный объект БД!';
    ERR_TCATEGORIESTATUS_DESTROY                = 'Ошибка уничтожения статуса категории!';
    ERR_TCATEGORIESTATUS_REGISTER_PROPERTY      = 'Ошибка регистрации свойства статуса категории!';
    ERR_TCATEGORIESTATUS_REGISTER_PROPERTIES    = 'Ошибка регистрации списка свойств статуса категории!';
    ERR_TCATEGORIESTATUS_GET_PROPERTY_AT        = 'Ошибка чтения свойства статуса категории по индексу!';
    ERR_TCATEGORIESTATUS_GET_PROPERTY_OF        = 'Ошибка чтения свойства статуса категории по имени!';
    ERR_TCATEGORIESTATUS_SET_PROPERTY_AT        = 'Ошибка записи свойства статуса категории по индексу!';
    ERR_TCATEGORIESTATUS_SET_PROPERTY_OF        = 'Ошибка записи свойства статуса категории по имени!';
    ERR_TCATEGORIESTATUS_GET_ID                 = 'Ошибка чтения идентификатора статуса категории!';
    ERR_TCATEGORIESTATUS_GET_ID_EXTERNAL        = 'Ошибка чтения названия статуса категории!';
    ERR_TCATEGORIESTATUS_GET_DESCRIPTION        = 'Ошибка чтения описания статуса категории!';
    ERR_TCATEGORIESTATUS_SET_ID                 = 'Ошибка записи идентификатора статуса категории!';
    ERR_TCATEGORIESTATUS_SET_ID_EXTERNAL        = 'Ошибка записи названия статуса категории!';
    ERR_TCATEGORIESTATUS_SET_DESCRIPTION        = 'Ошибка записи описания статуса категории!';
    ERR_TCATEGORIESTATUS_SET_OBJECT_NAME        = 'Ошибка записи наименования статуса категории!';
    ERR_TCATEGORIESTATUS_CHECK                  = 'Ошибка валидации статуса категории!';
    ERR_TCATEGORIESTATUS_LOAD                   = 'Ошибка загрузки статуса категории!';
    ERR_TCATEGORIESTATUS_SAVE                   = 'Ошибка сохранения статуса категории!';
    ERR_TCATEGORIESTATUS_DELETE                 = 'Ошибка удаления статуса категории!';
    ERR_TCATEGORIESTATUS_NOT_UNIQUE_ID          = 'Ошибка дублирования идентификатора статуса категории : ''%s'' = ''%s''!';
    ERR_TCATEGORIESTATUS_NOT_UNIQUE_ID_EXTERNAL = 'Ошибка дублирования названия статуса категории : ''%s'' = ''%s''!';
    ERR_TCATEGORIESTATUS_INVALID_ID             = 'Некорректный идентификатор статуса категории!';
    ERR_TCATEGORIESTATUS_INVALID_ID_EXTERNAL    = 'Некорректный название статуса категории!';
    ERR_TCATEGORIESTATUS_TRANSACTION            = 'Ошибка транзакции: '#13#10'%s';