{******************************************************************************}
{*  TKeyWords.err.inc                                                         *}
{*  Revolutionary Confederation of Anarcho Syndicalists                       *}
{*  Written by: black.rabbit 2012                                             *}
{******************************************************************************}
resourcestring
    ERR_TKEYWORDS                  = 'Ошибка списка ключевых слов!';
    ERR_TKEYWORDS_CREATE           = 'Ошибка создания списка ключевых слов!';
    ERR_TKEYWORDS_INVALID_DATABASE = 'Некорректный объект БД!';
    ERR_TKEYWORDS_INVALID_STREAM   = 'Некорректный поток!';
    ERR_TKEYWORDS_DESTROY          = 'Ошибка уничтожения списка ключевых слов!';
    ERR_TKEYWORDS_CHECK            = 'Ошибка валидации ключевого слова!';
    ERR_TKEYWORDS_GET_ITEM_AT      = 'Ошибка чтения ключевого слова по индексу!';
    ERR_TKEYWORDS_GET_ITEM_ON      = 'Ошибка чтения ключевого слова по идентификатору!';
    ERR_TKEYWORDS_SET_ITEM_AT      = 'Ошибка записи ключевого слова по индексу!';
    ERR_TKEYWORDS_SET_ITEM_ON      = 'Ошибка записи ключевого слова по идентификатору!';
    ERR_TKEYWORDS_ADD              = 'Ошибка добавления ключевого слова в список!';
    ERR_TKEYWORDS_ADD_LOAD         = 'Ошибка загрузки ключевого слова в список!';
    ERR_TKEYWORDS_ADD_SAVE         = 'Ошибка сохранения ключевого слова в список!';
    ERR_TKEYWORDS_FILTER           = 'Ошибка наложения фильтра!';
    ERR_TKEYWORDS_LOAD             = 'Ошибка загрузки списка ключевых слов!';
    ERR_TKEYWORDS_SAVE             = 'Ошибка сохранения списка ключевых слов!';
    ERR_TKEYWORDS_DELETE           = 'Ошибка удаления списка ключевых слов!';
    ERR_TKEYWORDS_TRANSACTION      = 'Ошибка транзакции: '#13#10'%s';
