{******************************************************************************}
{*  TKeyWord.err.inc                                                          *}
{*  Revolutionary Confederation of Anarcho Syndicalists                       *}
{*  Written by: black.rabbit 2012                                             *}
{******************************************************************************}
resourcestring
    ERR_TKEYWORD                        = 'Ошибка ключевого слова!';
    ERR_TKEYWORD_GET_ClASS_PROPERTIES   = 'Ошибка получения списка свойств класса ключевых слов!';
    ERR_TKEYWORD_CREATE                 = 'Ошибка создания ключевого слова!';
    ERR_TKEYWORD_CREATE_CLASS_TABLE     = 'Ошибка создания таблицы класса ключевых слов!';
    ERR_TKEYWORD_INVALID_DATABASE       = 'Некорректный объект БД!';
    ERR_TKEYWORD_DESTROY                = 'Ошибка уничтожения ключевого слова!';
    ERR_TKEYWORD_REGISTER_PROPERTY      = 'Ошибка регистрации свойства ключевого слова!';
    ERR_TKEYWORD_REGISTER_PROPERTIES    = 'Ошибка регистрации списка свойств ключевого слова!';
    ERR_TKEYWORD_GET_PROPERTY_AT        = 'Ошибка чтения свойства ключевого слова по индексу!';
    ERR_TKEYWORD_GET_PROPERTY_OF        = 'Ошибка чтения свойства ключевого слова по имени!';
    ERR_TKEYWORD_SET_PROPERTY_AT        = 'Ошибка записи свойства ключевого слова по индексу!';
    ERR_TKEYWORD_SET_PROPERTY_OF        = 'Ошибка записи свойства ключевого слова по имени!';
    ERR_TKEYWORD_GET_ID                 = 'Ошибка чтения идентификатора ключевого слова!';
    ERR_TKEYWORD_GET_KEY_WORD           = 'Ошибка чтения ключевого слова!';
    ERR_TKEYWORD_GET_HASH               = 'Ошибка чтения хэша ключевого слова!';
    ERR_TKEYWORD_GET_HASH_CATEGORIE     = 'Ошибка чтения хэш-ключа категории ключевого слова!';
    ERR_TKEYWORD_GET_ID_CATEGORIE       = 'Ошибка чтения идентификатора категории ключевого слова!';
    ERR_TKEYWORD_GET_HASH_MESSAGE       = 'Ошибка чтения хэш-ключа сообщения ключевого слова!';
    ERR_TKEYWORD_GET_ID_MESSAGE         = 'Ошибка чтения идентификатора сообщения ключевого слова!';
    ERR_TKEYWORD_GET_HASH_AUTHOR        = 'Ошибка чтения хэш-ключа автора ключевого слова!';
    ERR_TKEYWORD_GET_ID_AUTHOR          = 'Ошибка чтения идентификатора автора ключевого слова!';
    ERR_TKEYWORD_GET_AUTHOR             = 'Ошибка чтения автора ключевого слова!';
    ERR_TKEYWORD_GET_ID_OWNER           = 'Ошибка чтения идентификатора владельца ключевого слова!';
    ERR_TKEYWORD_GET_SALT               = 'Ошибка чтения соли ключевого слова!';
    ERR_TKEYWORD_SET_ID                 = 'Ошибка записи идентификатора ключевого слова!';
    ERR_TKEYWORD_SET_KEY_WORD           = 'Ошибка записи ключевого слова!';
    ERR_TKEYWORD_SET_HASH               = 'Ошибка записи хэша ключевого слова!';
    ERR_TKEYWORD_SET_HASH_CATEGORIE     = 'Ошибка записи хэш-ключа категории ключевого слова!';
    ERR_TKEYWORD_SET_ID_CATEGORIE       = 'Ошибка записи идентификатора категории ключевого слова!';
    ERR_TKEYWORD_SET_HASH_MESSAGE       = 'Ошибка записи хэш-ключа сообщения ключевого слова!';
    ERR_TKEYWORD_SET_ID_MESSAGE         = 'Ошибка записи идентификатора сообщения ключевого слова!';
    ERR_TKEYWORD_SET_HASH_AUTHOR        = 'Ошибка записи хэш-ключа автора ключевого слова!';
    ERR_TKEYWORD_SET_ID_AUTHOR          = 'Ошибка записи идентификатора автора ключевого слова!';
    ERR_TKEYWORD_SET_AUTHOR             = 'Ошибка записи автора ключевого слова!';
    ERR_TKEYWORD_SET_ID_OWNER           = 'Ошибка записи идентификатора владельца ключевого слова!';
    ERR_TKEYWORD_SET_SALT               = 'Ошибка записи соли ключевого слова!';
    ERR_TKEYWORD_CALC_HASH              = 'Ошибка вычисления хэша ключевого слова!';
    ERR_TKEYWORD_CHECK                  = 'Ошибка валидации ключевого слова!';
    ERR_TKEYWORD_LOAD                   = 'Ошибка загрузки ключевого слова!';
    ERR_TKEYWORD_LOAD_FROM_STREAM       = 'Ошибка импорта ключевого слова!';
    ERR_TKEYWORD_SAVE                   = 'Ошибка сохранения ключевого слова!';
    ERR_TKEYWORD_SAVE_TO_STREAM         = 'Ошибка экспорта ключевого слова!';
    ERR_TKEYWORD_DELETE                 = 'Ошибка удаления ключевого слова!';
    ERR_TKEYWORD_NOT_UNIQUE_ID          = 'Ошибка дублирования идентификатора ключевого слова : ''%s'' = ''%s''!';
    ERR_TKEYWORD_INVALID_ID             = 'Некорректный идентификатор ключевого слова!';
    ERR_TKEYWORD_INVALID_HASH           = 'Некорректный хэш ключевого слова!';
    ERR_TKEYWORD_INVALID_STREAM         = 'Некорректный поток!';
    ERR_TKEYWORD_TRANSACTION            = 'Ошибка транзакции: '#13#10'%s';
