{******************************************************************************}
{*  TMessageStatus.err.inc                                                    *}
{*  Revolutionary Confederation of Anarcho Syndicalists                       *}
{*  Written by: black.rabbit 2011                                             *}
{******************************************************************************}
resourcestring
    ERR_TMESSAGESTATUS                        = 'Ошибка статуса сообщения!';
    ERR_TMESSAGESTATUS_GET_ClASS_PROPERTIES   = 'Ошибка получения списка свойств класса статуса сообщений!';
    ERR_TMESSAGESTATUS_CREATE                 = 'Ошибка создания статуса сообщения!';
    ERR_TMESSAGESTATUS_CREATE_CLASS_TABLE     = 'Ошибка создания таблицы класса статуса сообщений!';
    ERR_TMESSAGESTATUS_INVALID_DATABASE       = 'Некорректный объект БД!';
    ERR_TMESSAGESTATUS_DESTROY                = 'Ошибка уничтожения статуса сообщения!';
    ERR_TMESSAGESTATUS_REGISTER_PROPERTY      = 'Ошибка регистрации свойства статуса сообщения!';
    ERR_TMESSAGESTATUS_REGISTER_PROPERTIES    = 'Ошибка регистрации списка свойств статуса сообщения!';
    ERR_TMESSAGESTATUS_GET_PROPERTY_AT        = 'Ошибка чтения свойства статуса сообщения по индексу!';
    ERR_TMESSAGESTATUS_GET_PROPERTY_OF        = 'Ошибка чтения свойства статуса сообщения по имени!';
    ERR_TMESSAGESTATUS_SET_PROPERTY_AT        = 'Ошибка записи свойства статуса сообщения по индексу!';
    ERR_TMESSAGESTATUS_SET_PROPERTY_OF        = 'Ошибка записи свойства статуса сообщения по имени!';
    ERR_TMESSAGESTATUS_GET_ID                 = 'Ошибка чтения идентификатора статуса сообщения!';
    ERR_TMESSAGESTATUS_GET_ID_EXTERNAL        = 'Ошибка чтения названия статуса сообщения!';
    ERR_TMESSAGESTATUS_GET_DESCRIPTION        = 'Ошибка чтения описания статуса сообщения!';
    ERR_TMESSAGESTATUS_SET_ID                 = 'Ошибка записи идентификатора статуса сообщения!';
    ERR_TMESSAGESTATUS_SET_ID_EXTERNAL        = 'Ошибка записи названия статуса сообщения!';
    ERR_TMESSAGESTATUS_SET_DESCRIPTION        = 'Ошибка записи описания статуса сообщения!';
    ERR_TMESSAGESTATUS_SET_OBJECT_NAME        = 'Ошибка записи наименования статуса сообщения!';
    ERR_TMESSAGESTATUS_CHECK                  = 'Ошибка валидации статуса сообщения!';
    ERR_TMESSAGESTATUS_LOAD                   = 'Ошибка загрузки статуса сообщения!';
    ERR_TMESSAGESTATUS_SAVE                   = 'Ошибка сохранения статуса сообщения!';
    ERR_TMESSAGESTATUS_DELETE                 = 'Ошибка удаления статуса сообщения!';
    ERR_TMESSAGESTATUS_NOT_UNIQUE_ID          = 'Ошибка дублирования идентификатора статуса сообщения : ''%s'' = ''%s''!';
    ERR_TMESSAGESTATUS_NOT_UNIQUE_ID_EXTERNAL = 'Ошибка дублирования названия статуса сообщения : ''%s'' = ''%s''!';
    ERR_TMESSAGESTATUS_INVALID_ID             = 'Некорректный идентификатор статуса сообщения!';
    ERR_TMESSAGESTATUS_INVALID_ID_EXTERNAL    = 'Некорректный название статуса сообщения!';
    ERR_TMESSAGESTATUS_TRANSACTION            = 'Ошибка транзакции: '#13#10'%s';