{******************************************************************************}
{*  TMessages.err.inc                                                         *}
{*  Revolutionary Confederation of Anarcho Syndicalists                       *}
{*  Written by: black.rabbit 2011                                             *}
{******************************************************************************}
resourcestring
    ERR_TMESSAGES                  = 'Ошибка списка сообщений!';
    ERR_TMESSAGES_CREATE           = 'Ошибка создания списка сообщений!';
    ERR_TMESSAGES_INVALID_DATABASE = 'Некорректный объект БД!';
    ERR_TMESSAGES_INVALID_STREAM   = 'Некорректный поток!';
    ERR_TMESSAGES_DESTROY          = 'Ошибка уничтожения списка сообщений!';
    ERR_TMESSAGES_CHECK            = 'Ошибка валидации сообщения!';
    ERR_TMESSAGES_GET_ITEM_AT      = 'Ошибка чтения сообщения по индексу!';
    ERR_TMESSAGES_GET_ITEM_OF      = 'Ошибка чтения сообщения по имени!';
    ERR_TMESSAGES_GET_ITEM_ON      = 'Ошибка чтения сообщения по идентификатору!';
    ERR_TMESSAGES_SET_ITEM_AT      = 'Ошибка записи сообщения по индексу!';
    ERR_TMESSAGES_SET_ITEM_OF      = 'Ошибка записи сообщения по имени!';
    ERR_TMESSAGES_SET_ITEM_ON      = 'Ошибка записи сообщения по идентификатору!';
    ERR_TMESSAGES_ADD              = 'Ошибка добавления сообщения в список!';
    ERR_TMESSAGES_ADD_LOAD         = 'Ошибка загрузки сообщения в список!';
    ERR_TMESSAGES_ADD_SAVE         = 'Ошибка сохранения сообщения в список!';
    ERR_TMESSAGES_FILTER           = 'Ошибка наложения фильтра!';
    ERR_TMESSAGES_LOAD             = 'Ошибка загрузки списка сообщений!';
    ERR_TMESSAGES_SAVE             = 'Ошибка сохранения списка сообщений!';
    ERR_TMESSAGES_DELETE           = 'Ошибка удаления списка сообщений!';
    ERR_TMESSAGES_FIND             = 'Ошибка поиска сообщения по хэшу!';
    ERR_TMESSAGES_GET_HASH_LIST    = 'Ошибка формирования хэш-таблицы!';
    ERR_TMESSAGES_REPLACE_PIC      = 'Ошибка замены иконки сообщения!';
    ERR_TMESSAGES_TRANSACTION      = 'Ошибка транзакции: '#13#10'%s';