{******************************************************************************}
{*  TMessageType.err.inc                                                      *}
{*  Revolutionary Confederation of Anarcho Syndicalists                       *}
{*  Written by: black.rabbit 2011                                             *}
{******************************************************************************}
resourcestring
    ERR_TMESSAGETYPE                        = 'Ошибка типа сообщения!';
    ERR_TMESSAGETYPE_GET_ClASS_PROPERTIES   = 'Ошибка получения списка свойств класса типа сообщений!';
    ERR_TMESSAGETYPE_CREATE                 = 'Ошибка создания типа сообщения!';
    ERR_TMESSAGETYPE_CREATE_CLASS_TABLE     = 'Ошибка создания таблицы класса типа сообщений!';
    ERR_TMESSAGETYPE_INVALID_DATABASE       = 'Некорректный объект БД!';
    ERR_TMESSAGETYPE_DESTROY                = 'Ошибка уничтожения типа сообщения!';
    ERR_TMESSAGETYPE_REGISTER_PROPERTY      = 'Ошибка регистрации свойства типа сообщения!';
    ERR_TMESSAGETYPE_REGISTER_PROPERTIES    = 'Ошибка регистрации списка свойств типа сообщения!';
    ERR_TMESSAGETYPE_GET_PROPERTY_AT        = 'Ошибка чтения свойства типа сообщения по индексу!';
    ERR_TMESSAGETYPE_GET_PROPERTY_OF        = 'Ошибка чтения свойства типа сообщения по имени!';
    ERR_TMESSAGETYPE_SET_PROPERTY_AT        = 'Ошибка записи свойства типа сообщения по индексу!';
    ERR_TMESSAGETYPE_SET_PROPERTY_OF        = 'Ошибка записи свойства типа сообщения по имени!';
    ERR_TMESSAGETYPE_GET_ID                 = 'Ошибка чтения идентификатора типа сообщения!';
    ERR_TMESSAGETYPE_GET_ID_EXTERNAL        = 'Ошибка чтения названия типа сообщения!';
    ERR_TMESSAGETYPE_GET_DESCRIPTION        = 'Ошибка чтения описания типа сообщения!';
    ERR_TMESSAGETYPE_SET_ID                 = 'Ошибка записи идентификатора типа сообщения!';
    ERR_TMESSAGETYPE_SET_ID_EXTERNAL        = 'Ошибка записи названия типа сообщения!';
    ERR_TMESSAGETYPE_SET_DESCRIPTION        = 'Ошибка записи описания типа сообщения!';
    ERR_TMESSAGETYPE_SET_OBJECT_NAME        = 'Ошибка записи наименования типа сообщения!';
    ERR_TMESSAGETYPE_CHECK                  = 'Ошибка валидации типа сообщения!';
    ERR_TMESSAGETYPE_LOAD                   = 'Ошибка загрузки типа сообщения!';
    ERR_TMESSAGETYPE_SAVE                   = 'Ошибка сохранения типа сообщения!';
    ERR_TMESSAGETYPE_DELETE                 = 'Ошибка удаления типа сообщения!';
    ERR_TMESSAGETYPE_NOT_UNIQUE_ID          = 'Ошибка дублирования идентификатора типа сообщения : ''%s'' = ''%s''!';
    ERR_TMESSAGETYPE_NOT_UNIQUE_ID_EXTERNAL = 'Ошибка дублирования названия типа сообщения : ''%s'' = ''%s''!';
    ERR_TMESSAGETYPE_INVALID_ID             = 'Некорректный идентификатор типа сообщения!';
    ERR_TMESSAGETYPE_INVALID_ID_EXTERNAL    = 'Некорректный название типа сообщения!';
    ERR_TMESSAGETYPE_TRANSACTION            = 'Ошибка транзакции: '#13#10'%s';
