{******************************************************************************}
{*  TPackages.err.inc                                                         *}
{*  Revolutionary Confederation of Anarcho Syndicalists                       *}
{*  Written by: black.rabbit 2011                                             *}
{******************************************************************************}
resourcestring
    ERR_TPACKAGES                  = 'Ошибка списка пакетов!';
    ERR_TPACKAGES_CREATE           = 'Ошибка создания списка пакетов!';
    ERR_TPACKAGES_INVALID_DATABASE = 'Некорректный объект БД!';
    ERR_TPACKAGES_INVALID_STREAM   = 'Некорректный поток!';
    ERR_TPACKAGES_DESTROY          = 'Ошибка уничтожения списка пакетов!';
    ERR_TPACKAGES_CHECK            = 'Ошибка валидации пакета!';
    ERR_TPACKAGES_GET_ITEM_AT      = 'Ошибка чтения пакета по индексу!';
    ERR_TPACKAGES_GET_ITEM_OF      = 'Ошибка чтения пакета по имени!';
    ERR_TPACKAGES_GET_ITEM_ON      = 'Ошибка чтения пакета по идентификатору!';
    ERR_TPACKAGES_SET_ITEM_AT      = 'Ошибка записи пакета по индексу!';
    ERR_TPACKAGES_SET_ITEM_OF      = 'Ошибка записи пакета по имени!';
    ERR_TPACKAGES_SET_ITEM_ON      = 'Ошибка записи пакета по идентификатору!';
    ERR_TPACKAGES_ADD              = 'Ошибка добавления пакета в список!';
    ERR_TPACKAGES_ADD_LOAD         = 'Ошибка загрузки пакета в список!';
    ERR_TPACKAGES_ADD_SAVE         = 'Ошибка сохранения пакета в список!';
    ERR_TPACKAGES_FILTER           = 'Ошибка наложения фильтра!';
    ERR_TPACKAGES_LOAD             = 'Ошибка загрузки списка пакетов!';
    ERR_TPACKAGES_LOAD_FROM_STREAM = 'Ошибка загрузки списка пакетов из потока!';
    ERR_TPACKAGES_SAVE             = 'Ошибка сохранения списка пакетов!';
    ERR_TPACKAGES_SAVE_TO_STREAM   = 'Ошибка сохранения списка пакетов в поток!';
    ERR_TPACKAGES_DELETE           = 'Ошибка удаления списка пакетов!';
    ERR_TPACKAGES_FIND             = 'Ошибка поиска пакета по хэшу!';
    ERR_TPACKAGES_GET_HASH_LIST    = 'Ошибка формирования хэш-таблицы!';
    ERR_TPACKAGES_TRANSACTION      = 'Ошибка транзакции: '#13#10'%s';
