{******************************************************************************}
{*  TPackageType.err.inc                                                      *}
{*  Revolutionary Confederation of Anarcho Syndicalists                       *}
{*  Written by: black.rabbit 2011                                             *}
{******************************************************************************}
resourcestring
    ERR_TPACKAGETYPE                        = 'Ошибка типа пакета!';
    ERR_TPACKAGETYPE_GET_ClASS_PROPERTIES   = 'Ошибка получения списка свойств класса типа пакетов!';
    ERR_TPACKAGETYPE_CREATE                 = 'Ошибка создания типа пакета!';
    ERR_TPACKAGETYPE_CREATE_CLASS_TABLE     = 'Ошибка создания таблицы класса типа пакетов!';
    ERR_TPACKAGETYPE_INVALID_DATABASE       = 'Некорректный объект БД!';
    ERR_TPACKAGETYPE_DESTROY                = 'Ошибка уничтожения типа пакета!';
    ERR_TPACKAGETYPE_REGISTER_PROPERTY      = 'Ошибка регистрации свойства типа пакета!';
    ERR_TPACKAGETYPE_REGISTER_PROPERTIES    = 'Ошибка регистрации списка свойств типа пакета!';
    ERR_TPACKAGETYPE_GET_PROPERTY_AT        = 'Ошибка чтения свойства типа пакета по индексу!';
    ERR_TPACKAGETYPE_GET_PROPERTY_OF        = 'Ошибка чтения свойства типа пакета по имени!';
    ERR_TPACKAGETYPE_SET_PROPERTY_AT        = 'Ошибка записи свойства типа пакета по индексу!';
    ERR_TPACKAGETYPE_SET_PROPERTY_OF        = 'Ошибка записи свойства типа пакета по имени!';
    ERR_TPACKAGETYPE_GET_ID                 = 'Ошибка чтения идентификатора типа пакета!';
    ERR_TPACKAGETYPE_GET_ID_EXTERNAL        = 'Ошибка чтения названия типа пакета!';
    ERR_TPACKAGETYPE_GET_DESCRIPTION        = 'Ошибка чтения описания типа пакета!';
    ERR_TPACKAGETYPE_SET_ID                 = 'Ошибка записи идентификатора типа пакета!';
    ERR_TPACKAGETYPE_SET_ID_EXTERNAL        = 'Ошибка записи названия типа пакета!';
    ERR_TPACKAGETYPE_SET_DESCRIPTION        = 'Ошибка записи описания типа пакета!';
    ERR_TPACKAGETYPE_SET_OBJECT_NAME        = 'Ошибка записи наименования типа пакета!';
    ERR_TPACKAGETYPE_CHECK                  = 'Ошибка валидации типа пакета!';
    ERR_TPACKAGETYPE_LOAD                   = 'Ошибка загрузки типа пакета!';
    ERR_TPACKAGETYPE_SAVE                   = 'Ошибка сохранения типа пакета!';
    ERR_TPACKAGETYPE_DELETE                 = 'Ошибка удаления типа пакета!';
    ERR_TPACKAGETYPE_NOT_UNIQUE_ID          = 'Ошибка дублирования идентификатора типа пакета : ''%s'' = ''%s''!';
    ERR_TPACKAGETYPE_NOT_UNIQUE_ID_EXTERNAL = 'Ошибка дублирования названия типа пакета : ''%s'' = ''%s''!';
    ERR_TPACKAGETYPE_INVALID_ID             = 'Некорректный идентификатор типа пакета!';
    ERR_TPACKAGETYPE_INVALID_ID_EXTERNAL    = 'Некорректный название типа пакета!';
    ERR_TPACKAGETYPE_TRANSACTION            = 'Ошибка транзакции: '#13#10'%s';
