{******************************************************************************}
{*  TPackageStatus.err.inc                                                    *}
{*  Revolutionary Confederation of Anarcho Syndicalists                       *}
{*  Written by: black.rabbit 2011                                             *}
{******************************************************************************}
resourcestring
    ERR_TPACKAGESTATUS                        = 'Ошибка статуса пакета!';
    ERR_TPACKAGESTATUS_GET_ClASS_PROPERTIES   = 'Ошибка получения списка свойств класса статуса пакетов!';
    ERR_TPACKAGESTATUS_CREATE                 = 'Ошибка создания статуса пакета!';
    ERR_TPACKAGESTATUS_CREATE_CLASS_TABLE     = 'Ошибка создания таблицы класса статуса пакетов!';
    ERR_TPACKAGESTATUS_INVALID_DATABASE       = 'Некорректный объект БД!';
    ERR_TPACKAGESTATUS_DESTROY                = 'Ошибка уничтожения статуса пакета!';
    ERR_TPACKAGESTATUS_REGISTER_PROPERTY      = 'Ошибка регистрации свойства статуса пакета!';
    ERR_TPACKAGESTATUS_REGISTER_PROPERTIES    = 'Ошибка регистрации списка свойств статуса пакета!';
    ERR_TPACKAGESTATUS_GET_PROPERTY_AT        = 'Ошибка чтения свойства статуса пакета по индексу!';
    ERR_TPACKAGESTATUS_GET_PROPERTY_OF        = 'Ошибка чтения свойства статуса пакета по имени!';
    ERR_TPACKAGESTATUS_SET_PROPERTY_AT        = 'Ошибка записи свойства статуса пакета по индексу!';
    ERR_TPACKAGESTATUS_SET_PROPERTY_OF        = 'Ошибка записи свойства статуса пакета по имени!';
    ERR_TPACKAGESTATUS_GET_ID                 = 'Ошибка чтения идентификатора статуса пакета!';
    ERR_TPACKAGESTATUS_GET_ID_EXTERNAL        = 'Ошибка чтения названия статуса пакета!';
    ERR_TPACKAGESTATUS_GET_DESCRIPTION        = 'Ошибка чтения описания статуса пакета!';
    ERR_TPACKAGESTATUS_SET_ID                 = 'Ошибка записи идентификатора статуса пакета!';
    ERR_TPACKAGESTATUS_SET_ID_EXTERNAL        = 'Ошибка записи названия статуса пакета!';
    ERR_TPACKAGESTATUS_SET_DESCRIPTION        = 'Ошибка записи описания статуса пакета!';
    ERR_TPACKAGESTATUS_SET_OBJECT_NAME        = 'Ошибка записи наименования статуса пакета!';
    ERR_TPACKAGESTATUS_CHECK                  = 'Ошибка валидации статуса пакета!';
    ERR_TPACKAGESTATUS_LOAD                   = 'Ошибка загрузки статуса пакета!';
    ERR_TPACKAGESTATUS_SAVE                   = 'Ошибка сохранения статуса пакета!';
    ERR_TPACKAGESTATUS_DELETE                 = 'Ошибка удаления статуса пакета!';
    ERR_TPACKAGESTATUS_NOT_UNIQUE_ID          = 'Ошибка дублирования идентификатора статуса пакета : ''%s'' = ''%s''!';
    ERR_TPACKAGESTATUS_NOT_UNIQUE_ID_EXTERNAL = 'Ошибка дублирования названия статуса пакета : ''%s'' = ''%s''!';
    ERR_TPACKAGESTATUS_INVALID_ID             = 'Некорректный идентификатор статуса пакета!';
    ERR_TPACKAGESTATUS_INVALID_ID_EXTERNAL    = 'Некорректный название статуса пакета!';
    ERR_TPACKAGESTATUS_TRANSACTION            = 'Ошибка транзакции: '#13#10'%s';