{******************************************************************************}
{*  TPics.err.inc                                                             *}
{*  Revolutionary Confederation of Anarcho Syndicalists                       *}
{*  Written by: black.rabbit 2011                                             *}
{******************************************************************************}
resourcestring
    ERR_TPICS                  = 'Ошибка списка иконок!';
    ERR_TPICS_CREATE           = 'Ошибка создания списка иконок!';
    ERR_TPICS_INVALID_DATABASE = 'Некорректный объект БД!';
    ERR_TPICS_DESTROY          = 'Ошибка уничтожения списка иконок!';
    ERR_TPICS_CHECK            = 'Ошибка валидации иконки!';
    ERR_TPICS_GET_ITEM_AT      = 'Ошибка чтения иконки по индексу!';
    ERR_TPICS_GET_ITEM_OF      = 'Ошибка чтения иконки по имени!';
    ERR_TPICS_GET_ITEM_ON      = 'Ошибка чтения иконки по идентификатору!';
    ERR_TPICS_SET_ITEM_AT      = 'Ошибка записи иконки по индексу!';
    ERR_TPICS_SET_ITEM_OF      = 'Ошибка записи иконки по имени!';
    ERR_TPICS_SET_ITEM_ON      = 'Ошибка записи иконки по идентификатору!';
    ERR_TPICS_ADD              = 'Ошибка добавления иконки в список!';
    ERR_TPICS_ADD_LOAD         = 'Ошибка загрузки иконки в список!';
    ERR_TPICS_ADD_SAVE         = 'Ошибка сохранения иконки в список!';
    ERR_TPICS_FILTER           = 'Ошибка наложения фильтра!';
    ERR_TPICS_LOAD             = 'Ошибка загрузки списка иконок!';
    ERR_TPICS_SAVE             = 'Ошибка сохранения списка иконок!';
    ERR_TPICS_DELETE           = 'Ошибка удаления списка иконок!';
    ERR_TPICS_FIND             = 'Ошибка поиска иконки по хэшу!';
    ERR_TPICS_TRANSACTION      = 'Ошибка транзакции: '#13#10'%s';
