{******************************************************************************}
{*  TUsers.err.inc                                                            *}
{*  Revolutionary Confederation of Anarcho Syndicalists                       *}
{*  Written by: black.rabbit 2011-2012                                        *}
{******************************************************************************}
resourcestring
    ERR_TUSERS                  = 'Ошибка списка пользователей!';
    ERR_TUSERS_CREATE           = 'Ошибка создания списка пользователей!';
    ERR_TUSERS_INVALID_DATABASE = 'Некорректный объект БД!';
    ERR_TUSERS_DESTROY          = 'Ошибка уничтожения списка пользователей!';
    ERR_TUSERS_CHECK            = 'Ошибка валидации пользователя!';
    ERR_TUSERS_GET_ITEM_AT      = 'Ошибка чтения пользователя по индексу!';
    ERR_TUSERS_GET_ITEM_OF      = 'Ошибка чтения пользователя по имени!';
    ERR_TUSERS_GET_ITEM_ON      = 'Ошибка чтения пользователя по идентификатору!';
    ERR_TUSERS_SET_ITEM_AT      = 'Ошибка записи пользователя по индексу!';
    ERR_TUSERS_SET_ITEM_OF      = 'Ошибка записи пользователя по имени!';
    ERR_TUSERS_SET_ITEM_ON      = 'Ошибка записи пользователя по идентификатору!';
    ERR_TUSERS_ADD              = 'Ошибка добавления пользователя в список!';
    ERR_TUSERS_ADD_LOAD         = 'Ошибка загрузки пользователя в список!';
    ERR_TUSERS_ADD_SAVE         = 'Ошибка сохранения пользователя в список!';
    ERR_TUSERS_FILTER           = 'Ошибка наложения фильтра!';
    ERR_TUSERS_LOAD             = 'Ошибка загрузки списка пользователей!';
    ERR_TUSERS_SAVE             = 'Ошибка сохранения списка пользователей!';
    ERR_TUSERS_DELETE           = 'Ошибка удаления списка пользователей!';
    ERR_TUSERS_FIND             = 'Ошибка поиска пользователя по хэшу!';
    ERR_TUSERS_GET_HASH_LIST    = 'Ошибка формирования хэш-таблицы!';
    ERR_TUSERS_REPLACE_PIC      = 'Ошибка замены иконки пользователя!'; 
    ERR_TUSERS_TRANSACTION      = 'Ошибка транзакции: '#13#10'%s';
