{******************************************************************************}
{*  UsersList.err.inc                                                         *}
{*  Revolutionary Confederation of Anarcho Syndicalists                       *}
{*  Written by: black.rabbit 2011                                             *}
{******************************************************************************}
{ ошибки при работе со списком пользователей }
resourcestring
    ERR_USERS_LIST_INCORRECT_DATABASE = 'Не инициализирован объект БД!';
    ERR_USERS_LIST_INCORRECT_NODES    = 'Объект списка не инициализирован!';
    ERR_USERS_LIST_CREATE             = 'Ошибка построения списка пользователей!';
    ERR_USERS_LIST_DELETE             = 'Ошибка очистки списка пользователей!';
    ERR_USERS_LIST_INCORRECT_ID       = 'Узел списка содержит некорректный идентификатор!';
    ERR_USERS_LIST_INCORRECT_NODE     = 'Объект узла списка не инициализирован!';
    ERR_USERS_LIST_GET_NODE_ID        = 'Ошибка получения идентификатора из узла списка!';
