{******************************************************************************}
{*  png.project.inc                                                           *}
{*  Revolutionary Confederation of Anarcho Syndicalists                       *}
{*  Written by: black.rabbit 2011                                             *}
{******************************************************************************}
    zlibpas  in 'png/zlibpas.pas',
    pngextra in 'png/pngextra.pas',
    pngimage in 'png/pngimage.pas',
    pnglang  in 'png/pnglang.pas',