{******************************************************************************}
{*  xml.project.inc                                                           *}
{*  Revolutionary Confederation of Anarcho Syndicalists                       *}
{*  Written by: black.rabbit 2011                                             *}
{******************************************************************************}
    XMLUtils  in 'xml/XMLUtils.pas',
    XMLParser in 'xml/XMLParser.pas',
    XMLDOM    in 'xml/XMLDOM.pas',
