{******************************************************************************}
{*  TCrypto.err.inc                                                           *}
{*  Revolutionary Confederation of Anarcho Syndicalists                       *}
{*  Written by: black.rabbit 2011                                             *}
{******************************************************************************}
resourcestring
    ERR_TCRYPTO                      = 'Ошибка крипто-системы!';
    ERR_TCRYPTO_GET_ClASS_PROPERTIES = 'Ошибка получения списка свойств класса крипто-системы!';
    ERR_TCRYPTO_CREATE               = 'Ошибка создания крипто-системы!';
    ERR_TCRYPTO_CREATE_CLASS_TABLE   = 'Ошибка создания таблицы мета-класса!';
    ERR_TCRYPTO_INVALID_DATABASE     = 'Некорректный объект БД!';
    ERR_TCRYPTO_DESTROY              = 'Ошибка уничтожения крипто-системы!';
    ERR_TCRYPTO_REGISTER_PROPERTY    = 'Ошибка регистрации свойства крипто-системы!';
    ERR_TCRYPTO_REGISTER_PROPERTIES  = 'Ошибка регистрации списка свойств крипто-системы!';
    ERR_TCRYPTO_GET_PROPERTY_AT      = 'Ошибка чтения свойства крипто-системы по индексу!';
    ERR_TCRYPTO_GET_PROPERTY_OF      = 'Ошибка чтения свойства крипто-системы по имени!';
    ERR_TCRYPTO_SET_PROPERTY_AT      = 'Ошибка записи свойства крипто-системы по индексу!';
    ERR_TCRYPTO_SET_PROPERTY_OF      = 'Ошибка записи свойства крипто-системы по имени!';
    ERR_TCRYPTO_GET_ALG_ASYMMETRIC   = 'Ошибка чтения алгоритма асимметричного шифрования!';
    ERR_TCRYPTO_GET_ALG_SYMMETRIC    = 'Ошибка чтения алгоритма симметричного шифрования!';
    ERR_TCRYPTO_GET_MODE_SYMMETRIC   = 'Ошибка чтения режима симметричного шифрования!';
    ERR_TCRYPTO_GET_ALG_HASH         = 'Ошибка чтения хэш-функции!';
    ERR_TCRYPTO_GET_GEN_RANDOM       = 'Ошибка чтения генератора псевдо-случайных чисел!';
    ERR_TCRYPTO_SET_ALG_ASYMMETRIC   = 'Ошибка записи алгоритма асимметричного шифрования!';
    ERR_TCRYPTO_SET_ALG_SYMMETRIC    = 'Ошибка записи алгоритма симметричного шифрования!';
    ERR_TCRYPTO_SET_MODE_SYMMETRIC   = 'Ошибка записи режима симметричного шифрования!';
    ERR_TCRYPTO_SET_ALG_HASH         = 'Ошибка записи хэш-функции!';
    ERR_TCRYPTO_SET_GEN_RANDOM       = 'Ошибка записи генератора псевдо-случайных чисел!';
    ERR_TCRYPTO_LOAD                 = 'Ошибка загрузки крипто-системы!';
    ERR_TCRYPTO_SAVE                 = 'Ошибка сохранения крипто-системы!';
    ERR_TCRYPTO_DELETE               = 'Ошибка удаления крипто-системы!';
    ERR_TCRYPTO_CHECK                = 'Ошибка валидации мета-объекта!';
    ERR_TCRYPTO_NOT_UNIQUE_ID        = 'Ошибка дублирования идентификатора крипто-системы : ''%s'' = ''%s''!';
    ERR_TCRYPTO_INVALID_ID           = 'Некорректный идентификатор крипто-системы!';
    ERR_TCRYPTO_TRANSACTION          = 'Ошибка транзакции: '#13#10'%s';
    ERR_TCRYPTO_RANDOM               = 'Ошибка генератора псевдо-случайных чисел!';
    ERR_TCRYPTO_HASH                 = 'Ошибка функции хэширования!';
    ERR_TCRYPTO_HMAC                 = 'Ошибка конструкции HMAC!';
    ERR_TCRYPTO_GENERATE_KEY         = 'Ошибка генерации сеансового ключа!';
    ERR_TCRYPTO_GENERATE_KEYS        = 'Ошибка генерации ключевой пары!';
    ERR_TCRYPTO_ENCRYPT_ASYMMETRIC   = 'Ошибка асимметричного шифрования данных!';
    ERR_TCRYPTO_DECRYPT_ASYMMETRIC   = 'Ошибка асимметричной дешифровки данных!';
    ERR_TCRYPTO_ENCRYPT_SYMMETRIC    = 'Ошибка симметричного шифрования данных!';
    ERR_TCRYPTO_DECRYPT_SYMMETRIC    = 'Ошибка симметричной дешифровки данных!';
    ERR_TCRYPTO_TEST_ASYMMETRIC      = 'Ошибка тестирования асимметричного шифра!';
    ERR_TCRYPTO_TEST_SYMMETRIC       = 'Ошибка тестирования симметричного шифра!';
    ERR_TCRYPTO_TEST_HASH            = 'Ошибка тестирования функции хэширования!';
    ERR_TCRYPTO_TEST_RANDOM          = 'Ошибка тестирования генератора псевдо-случайных чисел!';
