{******************************************************************************}
{*  TCryptoObjects.err.inc                                                    *}
{*  Revolutionary Confederation of Anarcho Syndicalists                       *}
{*  Written by: black.rabbit 2011                                             *}
{******************************************************************************}
resourcestring
    ERR_TCRYPTOOBJECTS             = 'Ошибка списка крипто-объектов!';
    ERR_TCRYPTOOBJECTS_CREATE      = 'Ошибка создания списка крипто-объектов!';
    ERR_TCRYPTOOBJECTS_DESTROY     = 'Ошибка уничтожения списка крипто-объектов!';
    ERR_TCRYPTOOBJECTS_CHECK       = 'Ошибка валидации крипто-объекта!';
    ERR_TCRYPTOOBJECTS_GET_ITEM_AT = 'Ошибка чтения крипто-объекта по индексу!';
    ERR_TCRYPTOOBJECTS_GET_ITEM_OF = 'Ошибка чтения крипто-объекта по имени!';
    ERR_TCRYPTOOBJECTS_SET_ITEM_AT = 'Ошибка записи крипто-объекта по индексу!';
    ERR_TCRYPTOOBJECTS_SET_ITEM_OF = 'Ошибка записи крипто-объекта по имени!';
    ERR_TCRYPTOOBJECTS_ADD         = 'Ошибка добавления крипто-объекта в список!';
