{******************************************************************************}
{*  TCryptoProperty.err.inc                                                   *}
{*  Revolutionary Confederation of Anarcho Syndicalists                       *}
{*  Written by: black.rabbit 2011                                             *}
{******************************************************************************}
resourcestring
    ERR_TCRYPTOPROPERTY                = 'Ошибка крипто-свойства!';
    ERR_TCRYPTOPROPERTY_CREATE         = 'Ошибка создания крипто-свойства!';
    ERR_TCRYPTOPROPERTY_DESTROY        = 'Ошибка уничтожения крипто-свойства!';
    ERR_TCRYPTOPROPERTY_UNKNOWN_TYPE   = 'Неизвестный тип данных крипто-свойства!';
    ERR_TCRYPTOPROPERTY_GET_VALUE      = 'Ошибка чтения данных крипто-свойства!';
    ERR_TCRYPTOPROPERTY_SET_VALUE      = 'Ошибка записи данных крипто-свойства!';
    ERR_TCRYPTOPROPERTY_ASSIGN         = 'Ощибка копирования крипто-свойства!';
    ERR_TCRYPTOPROPERTY_INVALID_CRYPTO = 'Некорректный объект крипто-системы!';
