{******************************************************************************}
{*  TCryptoObject.err.inc                                                     *}
{*  Revolutionary Confederation of Anarcho Syndicalists                       *}
{*  Written by: black.rabbit 2011                                             *}
{******************************************************************************}
resourcestring
    ERR_TCRYPTOOBJECT                      = 'Ошибка крипто-объекта!';
    ERR_TCRYPTOOBJECT_GET_ClASS_PROPERTIES = 'Ошибка получения списка свойств крипто-класса!';
    ERR_TCRYPTOOBJECT_CREATE               = 'Ошибка создания крипто-объекта!';
    ERR_TCRYPTOOBJECT_DESTROY              = 'Ошибка уничтожения крипто-объекта!';
    ERR_TCRYPTOOBJECT_REGISTER_PROPERTY    = 'Ошибка регистрации свойства крипто-объекта!';
    ERR_TCRYPTOOBJECT_REGISTER_PROPERTIES  = 'Ошибка регистрации списка свойств крипто-объекта!';
    ERR_TCRYPTOOBJECT_GET_PROPERTY_AT      = 'Ошибка чтения свойства крипто-объекта по индексу!';
    ERR_TCRYPTOOBJECT_GET_PROPERTY_OF      = 'Ошибка чтения свойства крипто-объекта по имени!';
    ERR_TCRYPTOOBJECT_SET_PROPERTY_AT      = 'Ошибка записи свойства крипто-объекта по индексу!';
    ERR_TCRYPTOOBJECT_SET_PROPERTY_OF      = 'Ошибка записи свойства крипто-объекта по имени!';
    ERR_TCRYPTOOBJECT_CHECK                = 'Ошибка валидации крипто-объекта!';
