{******************************************************************************}
{*  THashItem.err.inc                                                         *}
{*  Revolutionary Confederation of Anarcho Syndicalists                       *}
{*  Written by: black.rabbit 2011                                             *}
{******************************************************************************}
resourcestring
    ERR_THASHITEM                       = 'Ошибка элемента хэш-таблицы!';
    ERR_THASHITEM_GET_ClASS_PROPERTIES  = 'Ошибка получения списка свойств класса элемента хэш-таблицы!';
    ERR_THASHITEM_CREATE                = 'Ошибка создания элемента хэш-таблицы!';
    ERR_THASHITEM_DESTROY               = 'Ошибка уничтожения элемента хэш-таблицы!';
    ERR_THASHITEM_REGISTER_PROPERTY     = 'Ошибка регистрации свойства элемента хэш-таблицы!';
    ERR_THASHITEM_REGISTER_PROPERTIES   = 'Ошибка регистрации списка свойств элемента хэш-таблицы!';
    ERR_THASHITEM_GET_PROPERTY_AT       = 'Ошибка чтения свойства элемента хэш-таблицы по индексу!';
    ERR_THASHITEM_GET_PROPERTY_OF       = 'Ошибка чтения свойства элемента хэш-таблицы по имени!';
    ERR_THASHITEM_SET_PROPERTY_AT       = 'Ошибка записи свойства элемента хэш-таблицы по индексу!';
    ERR_THASHITEM_SET_PROPERTY_OF       = 'Ошибка записи свойства элемента хэш-таблицы по имени!';
    ERR_THASHITEM_CHECK                 = 'Ошибка валидации элемента хэш-таблицы!';
    ERR_THASHITEM_GET_KEY_HASH          = 'Ошибка чтения хэш-ключа элемента хэш-таблицы!';
    ERR_THASHITEM_GET_DATA_HASH         = 'Ошибка чтения хэша данных элемента хэш-таблицы!';
    ERR_THASHITEM_GET_TIME_STAMP_VECTOR = 'Ошибка чтения векторного времени элемента хэш-таблицы!';
    ERR_THASHITEM_SET_KEY_HASH          = 'Ошибка записи хэш-ключа элемента хэш-таблицы!';
    ERR_THASHITEM_SET_DATA_HASH         = 'Ошибка записи хэша данных элемента хэш-таблицы!';
    ERR_THASHITEM_SET_TIME_STAMP_VECTOR = 'Ошибка записи векторного времени элемента хэш-таблицы!';
    ERR_THASHITEM_INVALID_KEY_HASH      = 'Некорректный хэш-ключ!';
    ERR_THASHITEM_INVALID_DATA_HASH     = 'Некорректный хэш данных!';
