{******************************************************************************}
{*  THashList.err.inc                                                         *}
{*  Revolutionary Confederation of Anarcho Syndicalists                       *}
{*  Written by: black.rabbit 2011                                             *}
{******************************************************************************}
resourcestring
    ERR_THASHLIST                       = 'Ошибка хэш-таблицы!';
    ERR_THASHLIST_CREATE                = 'Ошибка создания хэш-таблицы!';
    ERR_THASHLIST_DESTROY               = 'Ошибка уничтожения хэш-таблицы!';
    ERR_THASHLIST_CHECK                 = 'Ошибка валидации элемента хэш-таблицы!';
    ERR_THASHLIST_GET_ITEM_AT           = 'Ошибка чтения элемента хэш-таблицы по индексу!';
    ERR_THASHLIST_GET_ITEM_OF           = 'Ошибка чтения элемента хэш-таблицы по имени!';
    ERR_THASHLIST_SET_ITEM_AT           = 'Ошибка записи элемента хэш-таблицы по индексу!';
    ERR_THASHLIST_SET_ITEM_OF           = 'Ошибка записи элемента хэш-таблицы по имени!';
    ERR_THASHLIST_ADD                   = 'Ошибка добавления элемента хэш-таблицы в список!';
    ERR_THASHLIST_CALC_MERCLE_KEY_HASH  = 'Ошибка вычисления ветви дерева Меркле для списка хэшей-ключей!';
    ERR_THASHLIST_CALC_MERCLE_DATA_HASH = 'Ошибка вычисления ветви дерева Меркле для списка хэшей данных!';
    ERR_THASHLIST_LOAD_FROM_STREAM      = 'Ошибка импорта хэш-таблицы!';
    ERR_THASHLIST_SAVE_TO_STREAM        = 'Ошибка экспорта хэш-таблицы!';
    ERR_THASHLIST_INVALID_STREAM        = 'Некорректный поток!';
    ERR_THASHLIST_INVALID_LIST          = 'Некорректная хэш-таблица!';
    ERR_THASHLIST_INVALID_ITEM          = 'Некорректный элемент хэш-таблицы!';
    ERR_THASHLIST_SUBSTRACT             = 'Ошибка вычитания хэш-таблиц!';
    ERR_THASHLIST_EXTRACT               = 'Ошибка экстракции обновлений хэш-таблицы!';
    ERR_THASHLIST_COMPARE               = 'Ошибка сравнения элементов хэш-таблицы!';
