{******************************************************************************}
{*  THyperObject.err.inc                                                      *}
{*  Revolutionary Confederation of Anarcho Syndicalists                       *}
{*  Written by: black.rabbit & rat 2011                                       *}
{******************************************************************************}
resourcestring
    ERR_THYPEROBJECT                        = 'Ошибка гипер-объекта!';
    ERR_THYPEROBJECT_GET_ClASS_PROPERTIES   = 'Ошибка получения списка свойств гипер-класса!';
    ERR_THYPEROBJECT_CREATE                 = 'Ошибка создания гипер-объекта!';
    ERR_THYPEROBJECT_CREATE_CLASS_TABLE     = 'Ошибка создания таблицы гипер-класса!';
    ERR_THYPEROBJECT_INVALID_DATABASE       = 'Некорректный объект БД!';
    ERR_THYPEROBJECT_DESTROY                = 'Ошибка уничтожения гипер-объекта!';
    ERR_THYPEROBJECT_REGISTER_PROPERTY      = 'Ошибка регистрации свойства гипер-объекта!';
    ERR_THYPEROBJECT_REGISTER_PROPERTIES    = 'Ошибка регистрации списка свойств гипер-объекта!';
    ERR_THYPEROBJECT_GET_PROPERTY_AT        = 'Ошибка чтения свойства гипер-объекта по индексу!';
    ERR_THYPEROBJECT_GET_PROPERTY_OF        = 'Ошибка чтения свойства гипер-объекта по имени!';
    ERR_THYPEROBJECT_SET_PROPERTY_AT        = 'Ошибка записи свойства гипер-объекта по индексу!';
    ERR_THYPEROBJECT_SET_PROPERTY_OF        = 'Ошибка записи свойства гипер-объекта по имени!';
    ERR_THYPEROBJECT_GET_ID                 = 'Ошибка чтения идентификатора гипер-объекта!';
    ERR_THYPEROBJECT_GET_ID_EXTERNAL        = 'Ошибка чтения пара-идентификатора гипер-объекта!';
    ERR_THYPEROBJECT_GET_TIME_STAMP_CREATE  = 'Ошибка чтения даты и времени создания гипер-объекта!';
    ERR_THYPEROBJECT_GET_TIME_STAMP_MODIFY  = 'Ошибка чтения даты и времени последнего редактирования гипер-объекта!';
    ERR_THYPEROBJECT_GET_TIME_STAMP_PUBLIC  = 'Ошибка чтения даты и времени публикации гипер-объекта!';
    ERR_THYPEROBJECT_GET_TIME_STAMP_VECTOR  = 'Ошибка чтения значения векторных часов гипер-объекта!';
    ERR_THYPEROBJECT_GET_VERSION            = 'Ошибка чтения версии гипер-объекта!';
    ERR_THYPEROBJECT_GET_KEY_HASH           = 'Ошибка чтения хэша-ключа гипер-объекта!';
    ERR_THYPEROBJECT_GET_DATA_HASH          = 'Ошибка чтения хэша данных гипер-объекта!';
    ERR_THYPEROBJECT_SET_ID                 = 'Ошибка записи идентификатора гипер-объекта!';
    ERR_THYPEROBJECT_SET_ID_EXTERNAL        = 'Ошибка записи пара-идентификатора гипер-объекта!';
    ERR_THYPEROBJECT_SET_TIME_STAMP_CREATE  = 'Ошибка записи даты и времени создания гипер-объекта!';
    ERR_THYPEROBJECT_SET_TIME_STAMP_MODIFY  = 'Ошибка записи даты и времени последнего редактирования гипер-объекта!';
    ERR_THYPEROBJECT_SET_TIME_STAMP_PUBLIC  = 'Ошибка записи даты и времени публикации гипер-объекта!';
    ERR_THYPEROBJECT_SET_TIME_STAMP_VECTOR  = 'Ошибка записи значения векторных часов гипер-объекта!';
    ERR_THYPEROBJECT_SET_VERSION            = 'Ошибка записи версии гипер-объекта!';
    ERR_THYPEROBJECT_SET_KEY_HASH           = 'Ошибка записи хэша-ключа гипер-объекта!';
    ERR_THYPEROBJECT_CALC_KEY_HASH          = 'Ошибка вычисления хэш-функции ключа от гипер-объекта!';
    ERR_THYPEROBJECT_CALC_DATA_HASH         = 'Ошибка вычисления хэш-функции от данных гипер-объекта!';
    ERR_THYPEROBJECT_CHECK                  = 'Ошибка валидации гипер-объекта!';
    ERR_THYPEROBJECT_LOAD                   = 'Ошибка загрузки гипер-объекта!';
    ERR_THYPEROBJECT_LOAD_FROM_STREAM       = 'Ошибка импорта гипер-объекта!';
    ERR_THYPEROBJECT_SAVE                   = 'Ошибка сохранения гипер-объекта!';
    ERR_THYPEROBJECT_SAVE_TO_STREAM         = 'Ошибка экспорта гипер-объекта!';
    ERR_THYPEROBJECT_DELETE                 = 'Ошибка удаления гипер-объекта!';
    ERR_THYPEROBJECT_NOT_UNIQUE_ID          = 'Ошибка дублирования идентификатора гипер-объекта : ''%s'' = ''%s''!';
    ERR_THYPEROBJECT_NOT_UNIQUE_ID_EXTERNAL = 'Ошибка дублирования пара-идентификатора гипер-объекта : ''%s'' = ''%s''!';
    ERR_THYPEROBJECT_NOT_UNIQUE_HASH        = 'Ошибка дублирования хэша гипер-объекта : ''%s'' = ''%s''!';
    ERR_THYPEROBJECT_INVALID_ID             = 'Некорректный идентификатор гипер-объекта!';
    ERR_THYPEROBJECT_INVALID_ID_EXTERNAL    = 'Некорректный пара-идентификатор гипер-объекта!';
    ERR_THYPEROBJECT_INVALID_STREAM         = 'Некорректный поток!';
    ERR_THYPEROBJECT_TRANSACTION            = 'Ошибка транзакции: '#13#10'%s';