{******************************************************************************}
{*  THypoObjects.err.inc                                                      *}
{*  Revolutionary Confederation of Anarcho Syndicalists                       *}
{*  Written by: black.rabbit 2011                                             *}
{******************************************************************************}
resourcestring
    ERR_THYPOOBJECTS                  = 'Ошибка списка гипо-объектов!';
    ERR_THYPOOBJECTS_CREATE           = 'Ошибка создания списка гипо-объектов!';
    ERR_THYPOOBJECTS_INVALID_DATABASE = 'Некорректный объект БД!';
    ERR_THYPOOBJECTS_DESTROY          = 'Ошибка уничтожения списка гипо-объектов!';
    ERR_THYPOOBJECTS_CHECK            = 'Ошибка валидации гипо-объекта!';
    ERR_THYPOOBJECTS_GET_ITEM_AT      = 'Ошибка чтения гипо-объекта по индексу!';
    ERR_THYPOOBJECTS_GET_ITEM_OF      = 'Ошибка чтения гипо-объекта по имени!';
    ERR_THYPOOBJECTS_GET_ITEM_ON      = 'Ошибка чтения гипо-объекта по идентификатору!';
    ERR_THYPOOBJECTS_SET_ITEM_AT      = 'Ошибка записи гипо-объекта по индексу!';
    ERR_THYPOOBJECTS_SET_ITEM_OF      = 'Ошибка записи гипо-объекта по имени!';
    ERR_THYPOOBJECTS_SET_ITEM_ON      = 'Ошибка записи гипо-объекта по идентификатору!';
    ERR_THYPOOBJECTS_ADD              = 'Ошибка добавления гипо-объекта в список!';
    ERR_THYPOOBJECTS_ADD_LOAD         = 'Ошибка загрузки гипо-объекта в список!';
    ERR_THYPOOBJECTS_ADD_SAVE         = 'Ошибка сохранения гипо-объекта в список!';
    ERR_THYPOOBJECTS_FILTER           = 'Ошибка наложения фильтра!';
    ERR_THYPOOBJECTS_LOAD             = 'Ошибка загрузки списка гипо-объектов!';
    ERR_THYPOOBJECTS_SAVE             = 'Ошибка сохранения списка гипо-объектов!';
    ERR_THYPOOBJECTS_DELETE           = 'Ошибка удаления списка гипо-объектов!';
    ERR_THYPOOBJECTS_FIND             = 'Ошибка поиска гипо-объекта по хэшу!';
    ERR_THYPOOBJECTS_GET_HASHES       = 'Ошибка получения хэш-таблицы списка гипо-объектов!'; 
    ERR_THYPOOBJECTS_TRANSACTION      = 'Ошибка транзакции: '#13#10'%s';