{******************************************************************************}
{*  THyperObjects.err.inc                                                      *}
{*  Revolutionary Confederation of Anarcho Syndicalists                       *}
{*  Written by: black.rabbit 2011                                             *}
{******************************************************************************}
resourcestring
    ERR_THYPEROBJECTS                  = 'Ошибка списка гипер-объектов!';
    ERR_THYPEROBJECTS_CREATE           = 'Ошибка создания списка гипер-объектов!';
    ERR_THYPEROBJECTS_INVALID_DATABASE = 'Некорректный объект БД!';
    ERR_THYPEROBJECTS_DESTROY          = 'Ошибка уничтожения списка гипер-объектов!';
    ERR_THYPEROBJECTS_CHECK            = 'Ошибка валидации гипер-объекта!';
    ERR_THYPEROBJECTS_GET_ITEM_AT      = 'Ошибка чтения гипер-объекта по индексу!';
    ERR_THYPEROBJECTS_GET_ITEM_OF      = 'Ошибка чтения гипер-объекта по имени!';
    ERR_THYPEROBJECTS_GET_ITEM_ON      = 'Ошибка чтения гипер-объекта по идентификатору!';
    ERR_THYPEROBJECTS_SET_ITEM_AT      = 'Ошибка записи гипер-объекта по индексу!';
    ERR_THYPEROBJECTS_SET_ITEM_OF      = 'Ошибка записи гипер-объекта по имени!';
    ERR_THYPEROBJECTS_SET_ITEM_ON      = 'Ошибка записи гипер-объекта по идентификатору!';
    ERR_THYPEROBJECTS_ADD              = 'Ошибка добавления гипер-объекта в список!';
    ERR_THYPEROBJECTS_ADD_LOAD         = 'Ошибка загрузки гипер-объекта в список!';
    ERR_THYPEROBJECTS_ADD_SAVE         = 'Ошибка сохранения гипер-объекта в список!';
    ERR_THYPEROBJECTS_FILTER           = 'Ошибка наложения фильтра!';
    ERR_THYPEROBJECTS_LOAD             = 'Ошибка загрузки списка гипер-объектов!';
    ERR_THYPEROBJECTS_SAVE             = 'Ошибка сохранения списка гипер-объектов!';
    ERR_THYPEROBJECTS_DELETE           = 'Ошибка удаления списка гипер-объектов!';
    ERR_THYPEROBJECTS_FIND             = 'Ошибка поиска гипер-объекта по хэшу!';
    ERR_THYPEROBJECTS_GET_HASHES       = 'Ошибка получения хэш-таблицы списка гипер-объектов!';
    ERR_THYPEROBJECTS_TRANSACTION      = 'Ошибка транзакции: '#13#10'%s';