{******************************************************************************}
{*  THypoObject.err.inc                                                       *}
{*  Revolutionary Confederation of Anarcho Syndicalists                       *}
{*  Written by: black.rabbit & rat 2011                                       *}
{******************************************************************************}
resourcestring
    ERR_THYPOOBJECT                       = 'Ошибка гипо-объекта!';
    ERR_THYPOOBJECT_GET_ClASS_PROPERTIES  = 'Ошибка получения списка свойств гипо-класса!';
    ERR_THYPOOBJECT_CREATE                = 'Ошибка создания гипо-объекта!';
    ERR_THYPOOBJECT_CREATE_CLASS_TABLE    = 'Ошибка создания таблицы гипо-класса!';
    ERR_THYPOOBJECT_INVALID_DATABASE      = 'Некорректный объект БД!';
    ERR_THYPOOBJECT_DESTROY               = 'Ошибка уничтожения гипо-объекта!';
    ERR_THYPOOBJECT_REGISTER_PROPERTY     = 'Ошибка регистрации свойства гипо-объекта!';
    ERR_THYPOOBJECT_REGISTER_PROPERTIES   = 'Ошибка регистрации списка свойств гипо-объекта!';
    ERR_THYPOOBJECT_GET_PROPERTY_AT       = 'Ошибка чтения свойства гипо-объекта по индексу!';
    ERR_THYPOOBJECT_GET_PROPERTY_OF       = 'Ошибка чтения свойства гипо-объекта по имени!';
    ERR_THYPOOBJECT_SET_PROPERTY_AT       = 'Ошибка записи свойства гипо-объекта по индексу!';
    ERR_THYPOOBJECT_SET_PROPERTY_OF       = 'Ошибка записи свойства гипо-объекта по имени!';
    ERR_THYPOOBJECT_GET_ID                = 'Ошибка чтения идентификатора гипо-объекта!';
    ERR_THYPOOBJECT_GET_TIME_STAMP_CREATE = 'Ошибка чтения даты и времени создания гипо-объекта!';
    ERR_THYPOOBJECT_GET_TIME_STAMP_MODIFY = 'Ошибка чтения даты и времени последнего редактирования гипо-объекта!';
    ERR_THYPOOBJECT_GET_TIME_STAMP_PUBLIC = 'Ошибка чтения даты и времени публикации гипо-объекта!';
    ERR_THYPOOBJECT_GET_TIME_STAMP_VECTOR = 'Ошибка чтения значения векторных часов гипо-объекта!';
    ERR_THYPOOBJECT_GET_VERSION           = 'Ошибка чтения версии гипо-объекта!';
    ERR_THYPOOBJECT_GET_KEY_HASH          = 'Ошибка чтения хэша-ключа гипо-объекта!';
    ERR_THYPOOBJECT_GET_DATA_HASH         = 'Ошибка чтения хэша данных гипо-объекта!';
    ERR_THYPOOBJECT_SET_ID                = 'Ошибка записи идентификатора гипо-объекта!';
    ERR_THYPOOBJECT_SET_TIME_STAMP_CREATE = 'Ошибка записи даты и времени создания гипо-объекта!';
    ERR_THYPOOBJECT_SET_TIME_STAMP_MODIFY = 'Ошибка записи даты и времени последнего редактирования гипо-объекта!';
    ERR_THYPOOBJECT_SET_TIME_STAMP_PUBLIC = 'Ошибка записи даты и времени публикации гипо-объекта!';
    ERR_THYPOOBJECT_SET_TIME_STAMP_VECTOR = 'Ошибка записи значения векторных часов гипо-объекта!';
    ERR_THYPOOBJECT_SET_VERSION           = 'Ошибка записи версии гипо-объекта!';
    ERR_THYPOOBJECT_SET_KEY_HASH          = 'Ошибка записи хэша-ключа гипо-объекта!';
    ERR_THYPOOBJECT_CALC_KEY_HASH         = 'Ошибка вычисления хэш-функции ключа от гипо-объекта!';
    ERR_THYPOOBJECT_CALC_DATA_HASH        = 'Ошибка вычисления хэш-функции от данных гипо-объекта!';
    ERR_THYPOOBJECT_CHECK                 = 'Ошибка валидации гипо-объекта!';
    ERR_THYPOOBJECT_LOAD                  = 'Ошибка загрузки гипо-объекта!';
    ERR_THYPOOBJECT_LOAD_FROM_STREAM      = 'Ошибка импорта гипо-объекта!';
    ERR_THYPOOBJECT_SAVE                  = 'Ошибка сохранения гипо-объекта!';
    ERR_THYPOOBJECT_SAVE_TO_STREAM        = 'Ошибка экспорта гипо-объекта!';
    ERR_THYPOOBJECT_DELETE                = 'Ошибка удаления гипо-объекта!';
    ERR_THYPOOBJECT_NOT_UNIQUE_ID         = 'Ошибка дублирования идентификатора гипо-объекта : ''%s'' = ''%s''!';
    ERR_THYPOOBJECT_NOT_UNIQUE_HASH       = 'Ошибка дублирования хэша гипо-объекта : ''%s'' = ''%s''!';
    ERR_THYPOOBJECT_INVALID_ID            = 'Некорректный идентификатор гипо-объекта!';
    ERR_THYPOOBJECT_INVALID_STREAM        = 'Некорректный поток!';
    ERR_THYPOOBJECT_TRANSACTION           = 'Ошибка транзакции: '#13#10'%s';