{******************************************************************************}
{*  TItems.err.inc                                                            *}
{*  Revolutionary Confederation of Anarcho Syndicalists                       *}
{*  Written by: black.rabbit 2011                                             *}
{******************************************************************************}
resourcestring
    ERR_TITEMS               = 'Ошибка списка!';
    ERR_TITEMS_CREATE        = 'Ошибка создания списка!';
    ERR_TITEMS_DESTROY       = 'Ошибка уничтожения списка!';
    ERR_TITEMS_GET_COUNT     = 'Ошибка подсчета количества элементов списка!';
    ERR_TITEMS_CHECK         = 'Ошибка валидации элемента списка!';
    ERR_TITEMS_GET_ITEM      = 'Ошибка чтения элемента списка!';
    ERR_TITEMS_GET_INDEX     = 'Ошибка чтения индекса элемента списка!';
    ERR_TITEMS_SET_ITEM      = 'Ошибка записи элемента списка!';
    ERR_TITEMS_SET_INDEX     = 'Ошибка записи индекса элемента списка!';
    ERR_TITEMS_OUT_OF_BOUNDS = 'Индекс %d выходит за пределы списка!';
    ERR_TITEMS_ASSIGN        = 'Ощибка копирования списка!';
    ERR_TITEMS_EQUALS        = 'Ошибка сравнения списков!';
    ERR_TITEMS_ADD           = 'Ошибка добавления элемента в список!';
    ERR_TITEMS_INSERT        = 'Ошибка вставки элемента в список!';
    ERR_TITEMS_MOVE          = 'Ошибка перемещения элемента списка!';
    ERR_TITEMS_COMPARE       = 'Ошибка сравнения элементов списка!';
    ERR_TITEMS_SORT          = 'Ошибка сортировки элементов списка';
    ERR_TITEMS_DELETE        = 'Ошибка удаления элемента из списка!';
    ERR_TITEMS_CLEAR         = 'Ошибка очистки списка!';
    ERR_TITEMS_FREE_ITEM     = 'Ошибка уничтожения элемента списка!';
    ERR_TITEMS_FREE_ALL      = 'Ошибка уничтожения элементов списка!';
