{******************************************************************************}
{*  TMetaProperty.err.inc                                                     *}
{*  Revolutionary Confederation of Anarcho Syndicalists                       *}
{*  Written by: black.rabbit 2011                                             *}
{******************************************************************************}
resourcestring
    ERR_TMETAPROPERTY                      = 'Ошибка мета-свойства!';
    ERR_TMETAPROPERTY_CREATE               = 'Ошибка создания мета-свойства!';
    ERR_TMETAPROPERTY_DESTROY              = 'Ошибка уничтожения мета-свойства!';
    ERR_TMETAPROPERTY_UNKNOWN_TYPE         = 'Неизвестный тип данных мета-свойства!';
    ERR_TMETAPROPERTY_GET_VALUE            = 'Ошибка чтения данных мета-свойства!';
    ERR_TMETAPROPERTY_SET_VALUE            = 'Ошибка записи данных мета-свойства!';
    ERR_TMETAPROPERTY_ASSIGN               = 'Ощибка копирования мета-свойства!';
    ERR_TMETAPROPERTY_GET_DB_TYPE          = 'Ошибка преобразования типа мета-свойства в тип поля БД!';
    ERR_TMETAPROPERTY_CAN_NOT_READ_STREAM  = 'Ошибка чтения данных из потока!';
    ERR_TMETAPROPERTY_CAN_NOT_WRITE_STREAM = 'Ошибка записи данных в поток!';
