{******************************************************************************}
{*  TMetaObjects.err.inc                                                      *}
{*  Revolutionary Confederation of Anarcho Syndicalists                       *}
{*  Written by: black.rabbit 2011                                             *}
{******************************************************************************}
resourcestring
    ERR_TMETAOBJECTS                  = 'Ошибка списка мета-объектов!';
    ERR_TMETAOBJECTS_CREATE           = 'Ошибка создания списка мета-объектов!';
    ERR_TMETAOBJECTS_INVALID_DATABASE = 'Некорректный объект БД!';
    ERR_TMETAOBJECTS_INVALID_STREAM   = 'Некорректный поток!';   
    ERR_TMETAOBJECTS_DESTROY          = 'Ошибка уничтожения списка мета-объектов!';
    ERR_TMETAOBJECTS_CHECK            = 'Ошибка валидации мета-объекта!';
    ERR_TMETAOBJECTS_GET_ITEM_AT      = 'Ошибка чтения мета-объекта по индексу!';
    ERR_TMETAOBJECTS_GET_ITEM_OF      = 'Ошибка чтения мета-объекта по имени!';
    ERR_TMETAOBJECTS_GET_ITEM_ON      = 'Ошибка чтения мета-объекта по идентификатору!';
    ERR_TMETAOBJECTS_SET_ITEM_AT      = 'Ошибка записи мета-объекта по индексу!';
    ERR_TMETAOBJECTS_SET_ITEM_OF      = 'Ошибка записи мета-объекта по имени!';
    ERR_TMETAOBJECTS_SET_ITEM_ON      = 'Ошибка записи мета-объекта по идентификатору!';
    ERR_TMETAOBJECTS_ADD              = 'Ошибка добавления мета-объекта в список!';
    ERR_TMETAOBJECTS_ADD_LOAD         = 'Ошибка загрузки мета-объекта в список!';
    ERR_TMETAOBJECTS_ADD_SAVE         = 'Ошибка сохранения мета-объекта в список!';
    ERR_TMETAOBJECTS_FILTER           = 'Ошибка наложения фильтра!';
    ERR_TMETAOBJECTS_ORDER            = 'Ошибка сортировки!';
    ERR_TMETAOBJECTS_LIMIT            = 'Ошибка фрагментации!';
    ERR_TMETAOBJECTS_GET_COUNT        = 'Ошибка подсчета элементов списка мета-объектов!';
    ERR_TMETAOBJECTS_LOAD             = 'Ошибка загрузки списка мета-объектов!';
    ERR_TMETAOBJECTS_LOAD_FROM_STREAM = 'Ошибка загрузки списка мета-объектов из потока!';
    ERR_TMETAOBJECTS_SAVE             = 'Ошибка сохранения списка мета-объектов!';
    ERR_TMETAOBJECTS_SAVE_TO_STREAM   = 'Ошибка сохранения списка мета-объектов в поток!';
    ERR_TMETAOBJECTS_DELETE           = 'Ошибка удаления списка мета-объектов!';
    ERR_TMETAOBJECTS_TRANSACTION      = 'Ошибка транзакции: '#13#10'%s';
    ERR_TMETAOBJECTS_COUNT_ERROR      = 'Ошибка SQL-функции COUNT () : '#13#10'Output error. Too many parameters: %d';
