{******************************************************************************}
{*  TMetaObject.err.inc                                                       *}
{*  Revolutionary Confederation of Anarcho Syndicalists                       *}
{*  Written by: black.rabbit 2011                                             *}
{******************************************************************************}
resourcestring
    ERR_TMETAOBJECT                      = 'Ошибка мета-объекта!';
    ERR_TMETAOBJECT_GET_ClASS_PROPERTIES = 'Ошибка получения списка свойств мета-класса!';
    ERR_TMETAOBJECT_CREATE               = 'Ошибка создания мета-объекта!';
    ERR_TMETAOBJECT_CREATE_CLASS_TABLE   = 'Ошибка создания таблицы мета-класса!';
    ERR_TMETAOBJECT_SET_DB               = 'Ошибка присвоения объекта БД!';
    ERR_TMETAOBJECT_INVALID_DATABASE     = 'Некорректный объект БД!';
    ERR_TMETAOBJECT_DESTROY              = 'Ошибка уничтожения мета-объекта!';
    ERR_TMETAOBJECT_REGISTER_PROPERTY    = 'Ошибка регистрации свойства мета-объекта!';
    ERR_TMETAOBJECT_REGISTER_PROPERTIES  = 'Ошибка регистрации списка свойств мета-объекта!';
    ERR_TMETAOBJECT_GET_PROPERTY_AT      = 'Ошибка чтения свойства мета-объекта по индексу!';
    ERR_TMETAOBJECT_GET_PROPERTY_OF      = 'Ошибка чтения свойства мета-объекта по имени!';
    ERR_TMETAOBJECT_SET_PROPERTY_AT      = 'Ошибка записи свойства мета-объекта по индексу!';
    ERR_TMETAOBJECT_SET_PROPERTY_OF      = 'Ошибка записи свойства мета-объекта по имени!';
    ERR_TMETAOBJECT_GET_ID               = 'Ошибка чтения идентификатора мета-объекта!';
    ERR_TMETAOBJECT_SET_ID               = 'Ошибка записи идентификатора мета-объекта!';
    ERR_TMETAOBJECT_CHECK                = 'Ошибка валидации мета-объекта!';
    ERR_TMETAOBJECT_LOAD                 = 'Ошибка загрузки мета-объекта!';
    ERR_TMETAOBJECT_LOAD_FROM_STREAM     = 'Ошибка импорта мета-объекта!';
    ERR_TMETAOBJECT_SAVE                 = 'Ошибка сохранения мета-объекта!';
    ERR_TMETAOBJECT_SAVE_TO_STREAM       = 'Ошибка экспорта мета-объекта!';
    ERR_TMETAOBJECT_DELETE               = 'Ошибка удаления мета-объекта!';
    ERR_TMETAOBJECT_NOT_UNIQUE_ID        = 'Ошибка дублирования идентификатора мета-объекта : ''%s'' = ''%s''!';
    ERR_TMETAOBJECT_NOT_FOUND_ID         = 'Ошибка: мета-объект с идентификатором ''%s'' = ''%s'' не найден в таблице ''%s''!';
    ERR_TMETAOBJECT_INVALID_ID           = 'Некорректный идентификатор мета-объекта!';
    ERR_TMETAOBJECT_INVALID_STREAM       = 'Некорректный поток!';
    ERR_TMETAOBJECT_TRANSACTION          = 'Ошибка транзакции: '#13#10'%s';
