{******************************************************************************}
{*  TParaObject.err.inc                                                       *}
{*  Revolutionary Confederation of Anarcho Syndicalists                       *}
{*  Written by: black.rabbit 2011                                             *}
{******************************************************************************}
resourcestring
    ERR_TPARAOBJECT                        = 'Ошибка пара-объекта!';
    ERR_TPARAOBJECT_GET_ClASS_PROPERTIES   = 'Ошибка получения списка свойств пара-класса!';
    ERR_TPARAOBJECT_CREATE                 = 'Ошибка создания пара-объекта!';
    ERR_TPARAOBJECT_CREATE_CLASS_TABLE     = 'Ошибка создания таблицы пара-класса!';
    ERR_TPARAOBJECT_INVALID_DATABASE       = 'Некорректный объект БД!';
    ERR_TPARAOBJECT_DESTROY                = 'Ошибка уничтожения пара-объекта!';
    ERR_TPARAOBJECT_REGISTER_PROPERTY      = 'Ошибка регистрации свойства пара-объекта!';
    ERR_TPARAOBJECT_REGISTER_PROPERTIES    = 'Ошибка регистрации списка свойств пара-объекта!';
    ERR_TPARAOBJECT_GET_PROPERTY_AT        = 'Ошибка чтения свойства пара-объекта по индексу!';
    ERR_TPARAOBJECT_GET_PROPERTY_OF        = 'Ошибка чтения свойства пара-объекта по имени!';
    ERR_TPARAOBJECT_SET_PROPERTY_AT        = 'Ошибка записи свойства пара-объекта по индексу!';
    ERR_TPARAOBJECT_SET_PROPERTY_OF        = 'Ошибка записи свойства пара-объекта по имени!';
    ERR_TPARAOBJECT_GET_ID                 = 'Ошибка чтения идентификатора пара-объекта!';
    ERR_TPARAOBJECT_GET_ID_EXTERNAL        = 'Ошибка чтения пара-идентификатора пара-объекта!';
    ERR_TPARAOBJECT_SET_ID                 = 'Ошибка записи идентификатора пара-объекта!';
    ERR_TPARAOBJECT_SET_ID_EXTERNAL        = 'Ошибка записи пара-идентификатора пара-объекта!';
    ERR_TPARAOBJECT_SET_OBJECT_NAME        = 'Ошибка записи наименования пара-объекта!';
    ERR_TPARAOBJECT_CHECK                  = 'Ошибка валидации пъара-объекта!';
    ERR_TPARAOBJECT_LOAD                   = 'Ошибка загрузки пара-объекта!';
    ERR_TPARAOBJECT_SAVE                   = 'Ошибка сохранения пара-объекта!';
    ERR_TPARAOBJECT_DELETE                 = 'Ошибка удаления пара-объекта!';
    ERR_TPARAOBJECT_NOT_UNIQUE_ID          = 'Ошибка дублирования идентификатора пара-объекта : ''%s'' = ''%s''!';
    ERR_TPARAOBJECT_NOT_UNIQUE_ID_EXTERNAL = 'Ошибка дублирования пара-идентификатора пара-объекта : ''%s'' = ''%s''!';
    ERR_TPARAOBJECT_INVALID_ID             = 'Некорректный идентификатор пара-объекта!';
    ERR_TPARAOBJECT_INVALID_ID_EXTERNAL    = 'Некорректный пара-идентификатор пара-объекта!';
    ERR_TPARAOBJECT_FIND                   = 'Ошибка поиска пара-идентификатора!';
    ERR_TPARAOBJECT_NOT_FOUND_ID           = 'Ошибка: пара-объект с идентификатором ''%s'' = ''%s'' не найден в таблице ''%s''!';
    ERR_TPARAOBJECT_NOT_FOUND_ID_EXTERNAL  = 'Ошибка: пара-объект с пара-идентификатором ''%s'' = ''%s'' не найден в таблице ''%s''!';
    ERR_TPARAOBJECT_TRANSACTION            = 'Ошибка транзакции: '#13#10'%s';
