{******************************************************************************}
{*  TParaObjects.err.inc                                                      *}
{*  Revolutionary Confederation of Anarcho Syndicalists                       *}
{*  Written by: black.rabbit 2011                                             *}
{******************************************************************************}
resourcestring
    ERR_TPARAOBJECTS                  = 'Ошибка списка пара-объектов!';
    ERR_TPARAOBJECTS_CREATE           = 'Ошибка создания списка пара-объектов!';
    ERR_TPARAOBJECTS_INVALID_DATABASE = 'Некорректный объект БД!';
    ERR_TPARAOBJECTS_DESTROY          = 'Ошибка уничтожения списка пара-объектов!';
    ERR_TPARAOBJECTS_CHECK            = 'Ошибка валидации пара-объекта!';
    ERR_TPARAOBJECTS_GET_ITEM_AT      = 'Ошибка чтения пара-объекта по индексу!';
    ERR_TPARAOBJECTS_GET_ITEM_OF      = 'Ошибка чтения пара-объекта по имени!';
    ERR_TPARAOBJECTS_GET_ITEM_ON      = 'Ошибка чтения пара-объекта по идентификатору!';
    ERR_TPARAOBJECTS_SET_ITEM_AT      = 'Ошибка записи пара-объекта по индексу!';
    ERR_TPARAOBJECTS_SET_ITEM_OF      = 'Ошибка записи пара-объекта по имени!';
    ERR_TPARAOBJECTS_SET_ITEM_ON      = 'Ошибка записи пара-объекта по идентификатору!';
    ERR_TPARAOBJECTS_ADD              = 'Ошибка добавления пара-объекта в список!';
    ERR_TPARAOBJECTS_ADD_LOAD         = 'Ошибка загрузки пара-объекта в список!';
    ERR_TPARAOBJECTS_ADD_SAVE         = 'Ошибка сохранения пара-объекта в список!';
    ERR_TPARAOBJECTS_FILTER           = 'Ошибка наложения фильтра!';
    ERR_TPARAOBJECTS_LOAD             = 'Ошибка загрузки списка пара-объектов!';
    ERR_TPARAOBJECTS_SAVE             = 'Ошибка сохранения списка пара-объектов!';
    ERR_TPARAOBJECTS_DELETE           = 'Ошибка удаления списка пара-объектов!';
    ERR_TPARAOBJECTS_TRANSACTION      = 'Ошибка транзакции: '#13#10'%s';
