{******************************************************************************}
{*  TProtoProperty.err.inc                                                    *}
{*  Revolutionary Confederation of Anarcho Syndicalists                       *}
{*  Written by: black.rabbit 2011                                             *}
{******************************************************************************}
resourcestring
    ERR_TPROTOPROPERTY              = 'Ошибка прото-свойства!';
    ERR_TPROTOPROPERTY_CREATE       = 'Ошибка создания прото-свойства!';
    ERR_TPROTOPROPERTY_DESTROY      = 'Ошибка уничтожения прото-свойства!';
    ERR_TPROTOPROPERTY_UNKNOWN_TYPE = 'Неизвестный тип данных прото-свойства!';
    ERR_TPROTOPROPERTY_GET_VALUE    = 'Ошибка чтения данных прото-свойства!';
    ERR_TPROTOPROPERTY_SET_VALUE    = 'Ошибка записи данных прото-свойства!';
    ERR_TPROTOPROPERTY_GET_MODE     = 'Ошибка чтения режима прото-свойства!';
    ERR_TPROTOPROPERTY_SET_MODE     = 'Ошибка записи режима прото-свойства!';
    ERR_TPROTOPROPERTY_ASSIGN       = 'Ощибка копирования прото-свойства!';
