{******************************************************************************}
{*  TProtoObjects.err.inc                                                     *}
{*  Revolutionary Confederation of Anarcho Syndicalists                       *}
{*  Written by: black.rabbit 2011                                             *}
{******************************************************************************}
resourcestring
    ERR_TPROTOOBJECTS             = 'Ошибка списка прото-объектов!';
    ERR_TPROTOOBJECTS_CREATE      = 'Ошибка создания списка прото-объектов!';
    ERR_TPROTOOBJECTS_DESTROY     = 'Ошибка уничтожения списка прото-объектов!';
    ERR_TPROTOOBJECTS_CHECK       = 'Ошибка валидации прото-объекта!';
    ERR_TPROTOOBJECTS_GET_ITEM_AT = 'Ошибка чтения прото-объекта по индексу!';
    ERR_TPROTOOBJECTS_GET_ITEM_OF = 'Ошибка чтения прото-объекта по имени!';
    ERR_TPROTOOBJECTS_SET_ITEM_AT = 'Ошибка записи прото-объекта по индексу!';
    ERR_TPROTOOBJECTS_SET_ITEM_OF = 'Ошибка записи прото-объекта по имени!';
    ERR_TPROTOOBJECTS_ADD         = 'Ошибка добавления прото-объекта в список!';
