{******************************************************************************}
{*  TProtoProperties.err.inc                                                  *}
{*  Revolutionary Confederation of Anarcho Syndicalists                       *}
{*  Written by: black.rabbit 2011                                             *}
{******************************************************************************}
resourcestring
    ERR_TPROTOPROPERTIES                    = 'Ошибка списка прото-свойств!';
    ERR_TPROTOPROPERTIES_CREATE             = 'Ошибка создания списка прото-свойств!';
    ERR_TPROTOPROPERTIES_DESTROY            = 'Ошибка уничтожения списка прото-свойств!';
    ERR_TPROTOPROPERTIES_CHECK              = 'Ошибка валидации прото-свойства!';
    ERR_TPROTOPROPERTIES_GET_ITEM_AT        = 'Ошибка чтения прото-свойства по индексу!';
    ERR_TPROTOPROPERTIES_GET_ITEM_OF        = 'Ошибка чтения прото-свойства по имени!';
    ERR_TPROTOPROPERTIES_SET_ITEM_AT        = 'Ошибка записи прото-свойства по индексу!';
    ERR_TPROTOPROPERTIES_SET_ITEM_OF        = 'Ошибка записи прото-свойства по имени!';
    ERR_TPROTOPROPERTIES_ADD                = 'Ошибка добавления прото-свойства в список!';
    ERR_TPROTOPROPERTIES_NOT_FOUND          = 'Свойство ''%s'' не найдено!';
    ERR_TPROTOPROPERTIES_INVALID_CLASS_TYPE = 'Некорректный экстра-класс свойства!';
    ERR_TPROTOPROPERTIES_REGISTER           = 'Ошибка регистрации экстра-свойства!';
