{******************************************************************************}
{*  TProtoObject.err.inc                                                      *}
{*  Revolutionary Confederation of Anarcho Syndicalists                       *}
{*  Written by: black.rabbit 2011                                             *}
{******************************************************************************}
resourcestring
    ERR_TPROTOOBJECT                      = 'Ошибка прото-объекта!';
    ERR_TPROTOOBJECT_GET_ClASS_PROPERTIES = 'Ошибка получения списка свойств прото-класса!';
    ERR_TPROTOOBJECT_CREATE               = 'Ошибка создания прото-объекта!';
    ERR_TPROTOOBJECT_DESTROY              = 'Ошибка уничтожения прото-объекта!';
    ERR_TPROTOOBJECT_REGISTER_PROPERTY    = 'Ошибка регистрации свойства прото-объекта!';
    ERR_TPROTOOBJECT_REGISTER_PROPERTIES  = 'Ошибка регистрации списка свойств прото-объекта!';
    ERR_TPROTOOBJECT_GET_PROPERTY_AT      = 'Ошибка чтения свойства прото-объекта по индексу!';
    ERR_TPROTOOBJECT_GET_PROPERTY_OF      = 'Ошибка чтения свойства прото-объекта по имени!';
    ERR_TPROTOOBJECT_SET_PROPERTY_AT      = 'Ошибка записи свойства прото-объекта по индексу!';
    ERR_TPROTOOBJECT_SET_PROPERTY_OF      = 'Ошибка записи свойства прото-объекта по имени!';
    ERR_TPROTOOBJECT_GET_OBJECT_NAME      = 'Ошибка чтения наименования прото-объекта!';
    ERR_TPROTOOBJECT_SET_OBJECT_NAME      = 'Ошибка записи наименования прото-объекта!';
    ERR_TPROTOOBJECT_ASSIGN               = 'Ощибка копирования прото-объекта!';
    ERR_TPROTOOBJECT_CHECK                = 'Ошибка валидации прото-объекта!';
    ERR_TPROTOOBJECT_ERROR                = 'Ошибка возбуждения исключения прото-объекта!';
