{******************************************************************************}
{*  Dialogs.project.inc                                                       *}
{*  Revolutionary Confederation of Anarcho Syndicalists                       *}
{*  Written by: black.rabbit 2011                                             *}
{******************************************************************************}
    DialogClasses         in 'dialogs/DialogClasses.pas',
    uProtoDialog          in 'dialogs/uProtoDialog.pas',
    uTextDialog           in 'dialogs/uTextDialog.pas',
    uExceptionDialog      in 'dialogs/uExceptionDialog.pas',
    uMetaDialog           in 'dialogs/uMetaDialog.pas',
{$IFNDEF MINI_CRYPTO}
    uWizardDialog         in 'dialogs/uWizardDialog.pas',
    uColorDialog          in 'dialogs/uColorDialog.pas',
    uIconDialog           in 'dialogs/uIconDialog.pas',
    uSmileDialog          in 'dialogs/uSmileDialog.pas',
    uLoginDialog          in 'dialogs/uLoginDialog.pas',
    uRegisterDialog       in 'dialogs/uRegisterDialog.pas',
    uCategorieDialog      in 'dialogs/uCategorieDialog.pas',
    uMessageDialog        in 'dialogs/uMessageDialog.pas',
    uUserDialog           in 'dialogs/uUserDialog.pas',
{$ENDIF MINI_CRYPTO}
    uRandomTestDialog     in 'dialogs/uRandomTestDialog.pas',
    uAsymmetricTestDialog in 'dialogs/uAsymmetricTestDialog.pas',
    uSymmetricTestDialog  in 'dialogs/uSymmetricTestDialog.pas',
    uHashTestDialog       in 'dialogs/uHashTestDialog.pas',
