{******************************************************************************}
{*  DiscreteMath.err.inc                                                      *}
{*  Revolutionary Confederation of Anarcho Syndicalists                       *}
{*  Written by: black.rabbit 2011                                             *}
{******************************************************************************}
resourcestring
    ERR_DISCRETE_MATH_GET_BUFFER    = 'Ошибка получения буфера!';
    ERR_DISCRETE_MATH_GET_FREQUENCY = 'Ошибка вычисления относительной частоты!';
    ERR_DISCRETE_MATH_GET_ENTROPY   = 'Ошибка вычисления информационной энтропии!';
    ERR_DISCRETE_MATH_GET_FFT       = 'Ошибка преобразования Фурье!';
    ERR_DISCRETE_MATH_DRAW_FUNCTION = 'Ошибка отрисовки графика дискретной функции!';
