{******************************************************************************}
{*  TDialogButton.err.inc                                                     *}
{*  Revolutionary Confederation of Anarcho Syndicalists                       *}
{*  Written by: black.rabbit 2011                                             *}
{******************************************************************************}
resourcestring
    ERR_TDIALOGBUTTON_CREATE  = 'Ошибка создания кнопки!';
    ERR_TDIALOGBUTTON_DESTROY = 'Ошибка уничтожения кнопки!';
    ERR_TDIALOGBUTTON_RESIZE  = 'Ошибка изменения размера кнопки!';
