{******************************************************************************}
{*  TDialogControls.err.inc                                                   *}
{*  Revolutionary Confederation of Anarcho Syndicalists                       *}
{*  Written by: black.rabbit 2011                                             *}
{******************************************************************************}
resourcestring
    ERR_TDIALOGCONTROLS                = 'Ошибка списка элементов управления диалогового окна!';
    ERR_TDIALOGCONTROLS_CREATE         = 'Ошибка создания списка элементов управления диалогового окна!';
    ERR_TDIALOGCONTROLS_DESTROY        = 'Ошибка уничтожения списка элементов управления диалогового окна!';
    ERR_TDIALOGCONTROLS_CHECK          = 'Ошибка валидации элемента управления диалогового окна!';
    ERR_TDIALOGCONTROLS_GET_ITEM_AT    = 'Ошибка чтения элемента управления диалогового окна по индексу!';
    ERR_TDIALOGCONTROLS_GET_ITEM_OF    = 'Ошибка чтения элемента управления диалогового окна по имени!';
    ERR_TDIALOGCONTROLS_GET_CAPTION_AT = 'Ошибка чтения заголовка элемента по индексу!';
    ERR_TDIALOGCONTROLS_GET_CAPTION_OF = 'Ошибка чтения заголовка элемента по имени!';
    ERR_TDIALOGCONTROLS_GET_VALUE_AT   = 'Ошибка чтения значения элемента по индексу!';
    ERR_TDIALOGCONTROLS_GET_VALUE_OF   = 'Ошибка чтения значения элемента по имени!';
    ERR_TDIALOGCONTROLS_SET_ITEM_AT    = 'Ошибка записи элемента управления диалогового окна по индексу!';
    ERR_TDIALOGCONTROLS_SET_ITEM_OF    = 'Ошибка записи элемента управления диалогового окна по имени!';
    ERR_TDIALOGCONTROLS_SET_CAPTION_AT = 'Ошибка записи заголовка элемента по индексу!';
    ERR_TDIALOGCONTROLS_SET_CAPTION_OF = 'Ошибка записи заголовка элемента по имени!';
    ERR_TDIALOGCONTROLS_SET_VALUE_AT   = 'Ошибка записи значения элемента по индексу!';
    ERR_TDIALOGCONTROLS_SET_VALUE_OF   = 'Ошибка записи значения элемента по имени!';
    ERR_TDIALOGCONTROLS_ADD            = 'Ошибка добавления элемента управления диалогового окна в список!';
    ERR_TDIALOGCONTROLS_DELETE         = 'Ошибка удаления элемента управления диалогового окна в список!';
    ERR_TDIALOGCONTROLS_CLEAR          = 'Ошибка очистки списка элементов управления диалогового окна!';
    ERR_TDIALOGCONTROLS_NOT_FOUND      = 'Элемент управления диалогового окна ''%s'' не найден!';
    ERR_TDIALOGCONTROLS_RESIZE         = 'Ошибка изменения размера списка элементов управления диалогового окна!';
