{******************************************************************************}
{*  TDialogControl.err.inc                                                    *}
{*  Revolutionary Confederation of Anarcho Syndicalists                       *}
{*  Written by: black.rabbit 2011                                             *}
{******************************************************************************}
resourcestring
    ERR_TDIALOGCONTROL_CREATE                 = 'Ошибка создания!';
    ERR_TDIALOGCONTROL_DESTROY                = 'Ошибка уничтожения!';
    ERR_TDIALOGCONTROL_GET_CONTROL_CLASS_TYPE = 'Ошибка получения инкапсулируемого класса!';
    ERR_TDIALOGCONTROL_GET_NAME               = 'Ошибка чтения имени!';
    ERR_TDIALOGCONTROL_GET_CAPTION            = 'Ошибка чтения заголовка!';
    ERR_TDIALOGCONTROL_GET_VALUE              = 'Ошибка чтения поля!';
    ERR_TDIALOGCONTROL_GET_READ_ONLY          = 'Ошибка чтения значения флага ''только для чтения''!';
    ERR_TDIALOGCONTROL_GET_VISIBLE            = 'Ошибка чтения значения параметра ''видимость''!';
    ERR_TDIALOGCONTROL_GET_POPUP_MENU         = 'Ошибка чтения контекстного меню!';
    ERR_TDIALOGCONTROL_SET_NAME               = 'Ошибка записи имени!';
    ERR_TDIALOGCONTROL_SET_CAPTION            = 'Ошибка записи заголовка!';
    ERR_TDIALOGCONTROL_SET_VALUE              = 'Ошибка записи поля!';
    ERR_TDIALOGCONTROL_SET_READ_ONLY          = 'Ошибка записи значения флага ''только для чтения''!';
    ERR_TDIALOGCONTROL_SET_VISIBLE            = 'Ошибка записи значения параметра ''видимость''!';
    ERR_TDIALOGCONTROL_SET_POPUP_MENU         = 'Ошибка записи контекстного меню!';

