{******************************************************************************}
{*  TDialogButtons.err.inc                                                    *}
{*  Revolutionary Confederation of Anarcho Syndicalists                       *}
{*  Written by: black.rabbit 2011                                             *}
{******************************************************************************}
resourcestring
    ERR_TDIALOGBUTTONS                = 'Ошибка списка диалоговых кнопок!';
    ERR_TDIALOGBUTTONS_CREATE         = 'Ошибка создания списка диалоговых кнопок!';
    ERR_TDIALOGBUTTONS_DESTROY        = 'Ошибка уничтожения списка диалоговых кнопок!';
    ERR_TDIALOGBUTTONS_CHECK          = 'Ошибка валидации диалоговой кнопки!';
    ERR_TDIALOGBUTTONS_GET_ITEM_AT    = 'Ошибка чтения диалоговой кнопки по индексу!';
    ERR_TDIALOGBUTTONS_GET_ITEM_OF    = 'Ошибка чтения диалоговой кнопки по имени!';
    ERR_TDIALOGBUTTONS_SET_ITEM_AT    = 'Ошибка записи диалоговой кнопки по индексу!';
    ERR_TDIALOGBUTTONS_SET_ITEM_OF    = 'Ошибка записи диалоговой кнопки по имени!';
    ERR_TDIALOGBUTTONS_ADD            = 'Ошибка добавления диалоговой кнопки в список!';
    ERR_TDIALOGBUTTONS_NOT_FOUND      = 'Диалоговая кнопка ''%s'' не найдена!';
    ERR_TDIALOGBUTTONS_SET_OWNER      = 'Ошибка присвоения владельца списку диалоговых кнопок!';
    ERR_TDIALOGBUTTONS_SET_IMAGE_LIST = 'Ошибка присвоения списка изображений списку диалоговых кнопок!';
    ERR_TDIALOGBUTTONS_SET_ON_CLICK   = 'Ошибка присвоения действия по умолчанию списку диалоговых кнопок!';
    ERR_TDIALOGBUTTONS_FREE_ALL       = 'Ошибка уничтожения диалоговой кнопки!';
