{******************************************************************************}
{*  TDialogFields.err.inc                                                     *}
{*  Revolutionary Confederation of Anarcho Syndicalists                       *}
{*  Written by: black.rabbit 2011                                             *}
{******************************************************************************}
resourcestring
    ERR_TDIALOGFIELDS             = 'Ошибка списка диалоговых полей!';
    ERR_TDIALOGFIELDS_CREATE      = 'Ошибка создания списка диалоговых полей!';
    ERR_TDIALOGFIELDS_DESTROY     = 'Ошибка уничтожения списка диалоговых полей!';
    ERR_TDIALOGFIELDS_CHECK       = 'Ошибка валидации диалогового поля!';
    ERR_TDIALOGFIELDS_GET_ITEM_AT = 'Ошибка чтения диалогового поля по индексу!';
    ERR_TDIALOGFIELDS_GET_ITEM_OF = 'Ошибка чтения диалогового поля по имени!';
    ERR_TDIALOGFIELDS_SET_ITEM_AT = 'Ошибка записи диалогового поля по индексу!';
    ERR_TDIALOGFIELDS_SET_ITEM_OF = 'Ошибка записи диалогового поля по имени!';
    ERR_TDIALOGFIELDS_ADD         = 'Ошибка добавления диалогового поля в список!';
    ERR_TDIALOGFIELDS_NOT_FOUND   = 'Поле ''%s'' не найдено!';