{******************************************************************************}
{*  TDialogField.err.inc                                                      *}
{*  Revolutionary Confederation of Anarcho Syndicalists                       *}
{*  Written by: black.rabbit 2011                                             *}
{******************************************************************************}
resourcestring
    ERR_TDIALOGFIELD              = 'Ошибка диалогового поля!';
    ERR_TDIALOGFIELD_CREATE       = 'Ошибка создания диалогового поля!';
    ERR_TDIALOGFIELD_DESTROY      = 'Ошибка уничтожения диалогового поля!';
    ERR_TDIALOGFIELD_UNKNOWN_TYPE = 'Неизвестный тип данных диалогового поля!';
    ERR_TDIALOGFIELD_GET_VALUE    = 'Ошибка чтения данных диалогового поля!';
    ERR_TDIALOGFIELD_SET_VALUE    = 'Ошибка записи данных диалогового поля!';
    ERR_TDIALOGFIELD_GET_MODE     = 'Ошибка чтения режима диалогового поля!';
    ERR_TDIALOGFIELD_SET_MODE     = 'Ошибка записи режима диалогового поля!';
    ERR_TDIALOGFIELD_ASSIGN       = 'Ощибка копирования диалогового поля!';