{******************************************************************************}
{*  ac.project.inc                                                            *}
{*  Revolutionary Confederation of Anarcho Syndicalists                       *}
{*  Written by: black.rabbit 2011                                             *}
{******************************************************************************}
    acpng  in 'ac/acpng.pas',
