{******************************************************************************}
{*  AES.uses.inc                                                              *}
{*  Revolutionary Confederation of Anarcho Syndicalists                       *}
{*  Written by: black.rabbit 2011                                             *}
{******************************************************************************}
{$IFNDEF EXTERNAL_LINK}
//  bTypes,
//  mem_util,
    aes_type,
    aes_base,
    aes_encr,
    aes_decr,
    aes_ecb,
    aes_cbc,
    aes_cfb,
//  aes_cfb8,
    aes_ofb,
    aes_ctr,
//  aes_cmac,
//  aes_omac,
//  aes_eax,
//  aes_cprf,
//  aes_xts,
//  aes_ccm,
//  aes_gcm,
{$ENDIF EXTERNAL_LINK}
