{******************************************************************************}
{*  AES.project.inc                                                           *}
{*  Revolutionary Confederation of Anarcho Syndicalists                       *}
{*  Written by: black.rabbit 2011                                             *}
{******************************************************************************}
{$IFNDEF EXTERNAL_LINK}
//  bTypes   in 'crypto/aes/bTypes.pas',
//  mem_util in 'crypto/aes/mem_util.pas',
    aes_type in 'crypto/aes/aes_type.pas',
    aes_base in 'crypto/aes/aes_base.pas',
    aes_encr in 'crypto/aes/aes_encr.pas',
    aes_decr in 'crypto/aes/aes_decr.pas',
    aes_ecb  in 'crypto/aes/aes_ecb.pas',
    aes_cbc  in 'crypto/aes/aes_cbc.pas',
    aes_cfb  in 'crypto/aes/aes_cfb.pas',
//  aes_cfb8 in 'crypto/aes/aes_cfb8.pas',
    aes_ofb  in 'crypto/aes/aes_ofb.pas',
    aes_ctr  in 'crypto/aes/aes_ctr.pas',
//  aes_cmac in 'crypto/aes/aes_cmac.pas',
//  aes_omac in 'crypto/aes/aes_omac.pas',
//  aes_eax  in 'crypto/aes/aes_eax.pas',
//  aes_cprf in 'crypto/aes/aes_cprf.pas',
//  aes_xts  in 'crypto/aes/aes_xts.pas',
//  aes_ccm  in 'crypto/aes/aes_ccm.pas',
//  aes_gcm  in 'crypto/aes/aes_gcm.pas',
{$ENDIF EXTERNAL_LINK}

