{******************************************************************************}
{*  Anubis.project.inc                                                        *}
{*  Revolutionary Confederation of Anarcho Syndicalists                       *}
{*  Written by: black.rabbit 2011                                             *}
{******************************************************************************}
{$IFNDEF EXTERNAL_LINK}
//  bTypes   in 'crypto/anubis/bTypes.pas',
//  mem_util in 'crypto/anubis/mem_util.pas',
    anu_base in 'crypto/anubis/anu_base.pas',
    anu_ecb  in 'crypto/anubis/anu_ecb.pas',
    anu_cbc  in 'crypto/anubis/anu_cbc.pas',
    anu_cfb  in 'crypto/anubis/anu_cfb.pas',
    anu_ofb  in 'crypto/anubis/anu_ofb.pas',
    anu_ctr  in 'crypto/anubis/anu_ctr.pas',
//  anu_omac in 'crypto/anubis/anu_omac.pas',
//  anu_eax  in 'crypto/anubis/anu_eax.pas',
{$ENDIF EXTERNAL_LINK}

