{******************************************************************************}
{*  BlowFish.uses.inc                                                         *}
{*  Revolutionary Confederation of Anarcho Syndicalists                       *}
{*  Written by: black.rabbit 2011                                             *}
{******************************************************************************}
{$IFNDEF EXTERNAL_LINK}
//  bTypes,
//  mem_util,
    bf_base,
    bf_ecb,
    bf_cbc,
    bf_cfb,
    bf_ofb,
    bf_ctr,
//  bf_omac,
//  bf_eax,
{$ENDIF EXTERNAL_LINK}
