{******************************************************************************}
{*  BlowFish.project.inc                                                      *}
{*  Revolutionary Confederation of Anarcho Syndicalists                       *}
{*  Written by: black.rabbit 2011                                             *}
{******************************************************************************}
{$IFNDEF EXTERNAL_LINK}
//  bTypes   in 'crypto/blowfish/bTypes.pas',
//  mem_util in 'crypto/blowfish/mem_util.pas',
    bf_base  in 'crypto/blowfish/bf_base.pas',
    bf_ecb   in 'crypto/blowfish/bf_ecb.pas',
    bf_cbc   in 'crypto/blowfish/bf_cbc.pas',
    bf_cfb   in 'crypto/blowfish/bf_cfb.pas',
    bf_ofb   in 'crypto/blowfish/bf_ofb.pas',
    bf_ctr   in 'crypto/blowfish/bf_ctr.pas',
//  bf_omac  in 'crypto/blowfish/bf_omac.pas',
//  bf_eax   in 'crypto/blowfish/bf_eax.pas',
{$ENDIF EXTERNAL_LINK}

