{******************************************************************************}
{*  Crypto.project.inc                                                        *}
{*  Revolutionary Confederation of Anarcho Syndicalists                       *}
{*  Written by: black.rabbit 2011                                             *}
{******************************************************************************}
  {$I 'crypto/PRNG.project.inc'}
  {$I 'crypto/RSA.project.inc'}
  {$I 'crypto/AES.project.inc'}
  {$I 'crypto/Anubis.project.inc'}
  {$I 'crypto/Serpent.project.inc'}
  {$I 'crypto/Shacal.project.inc'}
  {$I 'crypto/BlowFish.project.inc'}
  {$I 'crypto/TwoFish.project.inc'}
  Crypto in 'crypto/Crypto.pas',
