{******************************************************************************}
{*  PRNG.project.inc                                                          *}
{*  Revolutionary Confederation of Anarcho Syndicalists                       *}
{*  Written by: black.rabbit 2011                                             *}
{******************************************************************************}
{$IFNDEF EXTERNAL_LINK}
//  bTypes   in 'crypto/prng/bTypes.pas',
//  mem_util in 'crypto/prng/mem_util.pas',
    tsc      in 'crypto/prng/tsc.pas',
    hrtimer  in 'crypto/prng/hrtimer.pas',
    taus88   in 'crypto/prng/taus88.pas',
    taus113  in 'crypto/prng/taus113.pas',
    kiss123  in 'crypto/prng/kiss123.pas',
    tt800    in 'crypto/prng/tt800.pas',
    xor4096  in 'crypto/prng/xor4096.pas',
    mt19937  in 'crypto/prng/mt19937.pas',
//  aes_type in 'crypto/aes/aes_type.pas',
//  aes_base in 'crypto/aes/aes_base.pas',
//  aes_encr in 'crypto/aes/aes_encr.pas',
    aesr     in 'crypto/prng/aesr.pas',
    salsa20  in 'crypto/salsa/salsa20.pas',
    salsar   in 'crypto/prng/salsar.pas',
{$ENDIF EXTERNAL_LINK}
    isaac    in 'crypto/prng/isaac.pas',
