{******************************************************************************}
{*  PRNG.uses.inc                                                             *}
{*  Revolutionary Confederation of Anarcho Syndicalists                       *}
{*  Written by: black.rabbit 2011                                             *}
{******************************************************************************}
{$IFNDEF EXTERNAL_LINK}
//  bTypes,
//  mem_util,
    hrtimer,
    taus88,
    taus113,
    kiss123,
    tt800,
    xor4096,
    mt19937,
//  aes_type,
//  aes_base,
//  aes_encr,
    aesr,
    salsa20,
    salsar,
{$ENDIF EXTERNAL_LINK}
    isaac,