{******************************************************************************}
{*  RipeMD.err.inc                                                            *}
{*  Revolutionary Confederation of Anarcho Syndicalists                       *}
{*  Written by: black.rabbit 2011                                             *}
{******************************************************************************}
resourcestring
    ERR_RIPEMD128 = 'Ошибка вычисления хэш-функции RipeMD-128!';
    ERR_RIPEMD160 = 'Ошибка вычисления хэш-функции RipeMD-160!';
