{******************************************************************************}
{*  Serpent.project.inc                                                       *}
{*  Revolutionary Confederation of Anarcho Syndicalists                       *}
{*  Written by: black.rabbit 2011                                             *}
{******************************************************************************}
{$IFNDEF EXTERNAL_LINK}
//  bTypes   in 'crypto/serpent/bTypes.pas',
//  mem_util in 'crypto/serpent/mem_util.pas',
    sp_base  in 'crypto/serpent/sp_base.pas',
    sp_ecb   in 'crypto/serpent/sp_ecb.pas',
    sp_cbc   in 'crypto/serpent/sp_cbc.pas',
    sp_cfb   in 'crypto/serpent/sp_cfb.pas',
    sp_ofb   in 'crypto/serpent/sp_ofb.pas',
    sp_ctr   in 'crypto/serpent/sp_ctr.pas',
//  sp_omac  in 'crypto/serpent/sp_omac.pas',
//  sp_eax   in 'crypto/serpent/sp_eax.pas',
{$ENDIF EXTERNAL_LINK}

