{******************************************************************************}
{*  Serpent.uses.inc                                                          *}
{*  Revolutionary Confederation of Anarcho Syndicalists                       *}
{*  Written by: black.rabbit 2011                                             *}
{******************************************************************************}
{$IFNDEF EXTERNAL_LINK}
//  bTypes,
//  mem_util,
    sp_base,
    sp_ecb,
    sp_cbc,
    sp_cfb,
    sp_ofb,
    sp_ctr,
//  sp_omac,
//  sp_eax,
{$ENDIF EXTERNAL_LINK}
