{******************************************************************************}
{*  Shacal.project.inc                                                        *}
{*  Revolutionary Confederation of Anarcho Syndicalists                       *}
{*  Written by: black.rabbit 2011                                             *}
{******************************************************************************}
{$IFNDEF EXTERNAL_LINK}
//  bTypes   in 'crypto/shacal/bTypes.pas',
//  mem_util in 'crypto/shacal/mem_util.pas',
    sc_base  in 'crypto/shacal/sc_base.pas',
    sc_ecb   in 'crypto/shacal/sc_ecb.pas',
    sc_cbc   in 'crypto/shacal/sc_cbc.pas',
    sc_cfb   in 'crypto/shacal/sc_cfb.pas',
    sc_ofb   in 'crypto/shacal/sc_ofb.pas',
    sc_ctr   in 'crypto/shacal/sc_ctr.pas',
{$ENDIF EXTERNAL_LINK}

