{******************************************************************************}
{*  Shacal.uses.inc                                                           *}
{*  Revolutionary Confederation of Anarcho Syndicalists                       *}
{*  Written by: black.rabbit 2011                                             *}
{******************************************************************************}
{$IFNDEF EXTERNAL_LINK}
//  bTypes,
//  mem_util,
    sc_base,
    sc_ecb,
    sc_cbc,
    sc_cfb,
    sc_ofb,
    sc_ctr,
{$ENDIF EXTERNAL_LINK}
