{******************************************************************************}
{*  Tiger.err.inc                                                             *}
{*  Revolutionary Confederation of Anarcho Syndicalists                       *}
{*  Written by: black.rabbit 2011                                             *}
{******************************************************************************}
resourcestring
    ERR_TIGER128         = 'Ошибка вычисления хэш-функции Tiger-128!';
    ERR_TIGER160         = 'Ошибка вычисления хэш-функции Tiger-160!';
    ERR_TIGER192         = 'Ошибка вычисления хэш-функции Tiger-192!';
    ERR_TIGER            = 'Ошибка вычисления хэш-функции Tiger-%d!';
    ERR_LTH              = 'Ошибка вычисления LTH-%d!';
    ERR_ITH              = 'Ошибка вычисления ITH-%d!';
    ERR_TTR              = 'Ошибка вычисления TTR-%d!';
    ERR_TTH              = 'Ошибка вычисления конструкции TTH-%d!';
    ERR_TTH_INVALID_PART = 'Invalid TigerTree%d last part: ''%s''!';
