{******************************************************************************}
{*  TwoFish.uses.inc                                                          *}
{*  Revolutionary Confederation of Anarcho Syndicalists                       *}
{*  Written by: black.rabbit 2011                                             *}
{******************************************************************************}
{$IFNDEF EXTERNAL_LINK}
//  bTypes,
//  mem_util,
    tf_base,
    tf_ecb,
    tf_cbc,
    tf_cfb,
    tf_ofb,
    tf_ctr,
//  tf_omac,
//  tf_eax,
{$ENDIF EXTERNAL_LINK}
