{******************************************************************************}
{*  TwoFish.project.inc                                                       *}
{*  Revolutionary Confederation of Anarcho Syndicalists                       *}
{*  Written by: black.rabbit 2011                                             *}
{******************************************************************************}
{$IFNDEF EXTERNAL_LINK}
//  bTypes   in 'crypto/twofish/bTypes.pas',
//  mem_util in 'crypto/twofish/mem_util.pas',
    tf_base  in 'crypto/twofish/tf_base.pas',
    tf_ecb   in 'crypto/twofish/tf_ecb.pas',
    tf_cbc   in 'crypto/twofish/tf_cbc.pas',
    tf_cfb   in 'crypto/twofish/tf_cfb.pas',
    tf_ofb   in 'crypto/twofish/tf_ofb.pas',
    tf_ctr   in 'crypto/twofish/tf_ctr.pas',
//  tf_omac  in 'crypto/twofish/tf_omac.pas',
//  tf_eax   in 'crypto/twofish/tf_eax.pas',
{$ENDIF EXTERNAL_LINK}

